/**
 * Emergency cellular dispatch utilities for offline disaster scenarios.
 *
 * When mobile internet (4G/5G) is dead, baseband cellular signaling (SMS/Voice)
 * and emergency carrier roaming (112 / 1070) can still transmit across all
 * network operators (Jio, Airtel, BSNL, Vi) without mobile data.
 */

export const ASSAM_EMERGENCY_NUMBERS = {
  nationalEmergency: "112",
  stateEmergencyOperationsCentre: "1070",
  districtEmergencyOperationsCentre: "1077",
  fireAndRescue: "101",
  ambulance108: "108",
};

export type EmergencySmsOptions = {
  publicCode?: string;
  latitude: number;
  longitude: number;
  emergencyType?: string;
  peopleAffected?: number;
  locationLabel?: string;
  notes?: string;
  recipient?: string;
};

/**
 * Formats a compact, standardized emergency SMS text message optimized for
 * 2G/GSM cellular SMS transmission during severe network congestion.
 */
export function formatEmergencySmsText(options: EmergencySmsOptions): string {
  const code = options.publicCode || "SOS";
  const lat = options.latitude.toFixed(5);
  const lng = options.longitude.toFixed(5);
  const type = (options.emergencyType || "FLOOD").toUpperCase();
  const people = options.peopleAffected || 1;
  const loc = options.locationLabel ? ` @ ${options.locationLabel.slice(0, 40)}` : "";
  const notes = options.notes ? ` - ${options.notes.slice(0, 50)}` : "";

  return `ASSAM RESCUE SOS [${code}] LOC:${lat},${lng}${loc} TYPE:${type} PEOPLE:${people}${notes} (Auto-generated by Assam Rescue App)`;
}

/**
 * Builds a universal `sms:` URI compatible with both Android and iOS devices.
 * Android uses `sms:112?body=...` while older iOS uses `sms:112;&body=...` or `sms:112&body=...`.
 */
export function buildEmergencySmsUri(options: EmergencySmsOptions): string {
  const recipient = options.recipient || ASSAM_EMERGENCY_NUMBERS.nationalEmergency;
  const bodyText = formatEmergencySmsText(options);
  const encodedBody = encodeURIComponent(bodyText);

  const isIOS =
    typeof navigator !== "undefined" &&
    (/iPad|iPhone|iPod/.test(navigator.userAgent) ||
      (navigator.platform === "MacIntel" && navigator.maxTouchPoints > 1));

  if (isIOS) {
    return `sms:${recipient}&body=${encodedBody}`;
  }
  return `sms:${recipient}?body=${encodedBody}`;
}
