import { beforeEach, describe, expect, it } from "vitest";
import { appRouter } from "./routers";
import type { TrpcContext } from "./_core/context";
import { _memoryIncidents, _memoryMissionOffers, _memoryUsers } from "./rescue.db";

function contextFor(userId: number, role: "user" | "rescuer" | "admin" = "user"): TrpcContext {
  const now = new Date();
  return {
    user: {
      id: userId,
      openId: `test-user-${userId}`,
      name: `User ${userId}`,
      email: `user${userId}@example.com`,
      password: null,
      loginMethod: "test",
      role,
      status: "active",
      createdAt: now,
      updatedAt: now,
      lastSignedIn: now,
    },
    req: { protocol: "https", headers: {} } as TrpcContext["req"],
    res: {} as TrpcContext["res"],
  };
}

describe("SOS Cancellation Semantics & Authorization", () => {
  beforeEach(() => {
    _memoryIncidents.clear();
    _memoryMissionOffers.clear();
    _memoryUsers.clear();
  });

  it("allows the reporting citizen to cancel an active unassigned SOS during the cancellation window", async () => {
    const userCaller = appRouter.createCaller(contextFor(101, "user"));

    // 1. Create SOS
    const created = await userCaller.rescue.emergency.create({
      locationLabel: "Guwahati Riverside",
      latitude: 26.14,
      longitude: 91.73,
      emergencyType: "flood",
      severity: "high",
      peopleAffected: 1,
    });

    expect(created.publicCode).toBeDefined();

    // 2. Cancel SOS
    const cancelResult = await userCaller.rescue.emergency.cancel({
      publicCode: created.publicCode,
    });

    expect(cancelResult.success).toBe(true);
    expect(cancelResult.status).toBe("resolved");

    // Verify incident state in database/memory is resolved
    const stored = _memoryIncidents.get(created.incidentId);
    expect(stored?.status).toBe("resolved");
    expect(stored?.dispatchStatus).toBe("resolved");
  });

  it("cancels any active mission offers when citizen cancels the SOS", async () => {
    const userCaller = appRouter.createCaller(contextFor(102, "user"));

    const created = await userCaller.rescue.emergency.create({
      locationLabel: "Dispur, Guwahati",
      latitude: 26.15,
      longitude: 91.78,
      emergencyType: "flood",
      severity: "high",
      peopleAffected: 2,
    });

    // Simulate an active mission offer generated by dispatch engine
    _memoryMissionOffers.set(901, {
      id: 901,
      incidentId: created.incidentId,
      rescuerId: 201,
      distanceKm: 1.5,
      matchScore: 950,
      status: "offered",
      offeredAt: new Date(),
      expiresAt: new Date(Date.now() + 10_000),
      respondedAt: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    });

    // Cancel SOS
    await userCaller.rescue.emergency.cancel({
      incidentId: created.incidentId,
    });

    // Verify offer status changed to cancelled
    const offer = _memoryMissionOffers.get(901);
    expect(offer?.status).toBe("cancelled");
  });

  it("prevents User A from cancelling User B's SOS (IDOR protection)", async () => {
    const victimCaller = appRouter.createCaller(contextFor(103, "user"));
    const attackerCaller = appRouter.createCaller(contextFor(104, "user"));

    const created = await victimCaller.rescue.emergency.create({
      locationLabel: "Panbazar, Guwahati",
      latitude: 26.18,
      longitude: 91.74,
      emergencyType: "medical",
      severity: "critical",
      peopleAffected: 1,
    });

    // Attacker tries to cancel victim's SOS
    await expect(
      attackerCaller.rescue.emergency.cancel({
        publicCode: created.publicCode,
      })
    ).rejects.toMatchObject({
      code: "FORBIDDEN",
      message: /Only the SOS reporter can cancel/i,
    });
  });

  it("rejects cancellation if the incident is already assigned to a responder", async () => {
    const userCaller = appRouter.createCaller(contextFor(105, "user"));

    const created = await userCaller.rescue.emergency.create({
      locationLabel: "Ulubari, Guwahati",
      latitude: 26.17,
      longitude: 91.76,
      emergencyType: "trapped",
      severity: "critical",
      peopleAffected: 3,
    });

    // Simulate rescuer assignment
    const mem = _memoryIncidents.get(created.incidentId)!;
    mem.status = "dispatched";
    mem.assignedRescuerId = 301;
    _memoryIncidents.set(created.incidentId, mem);

    await expect(
      userCaller.rescue.emergency.cancel({
        publicCode: created.publicCode,
      })
    ).rejects.toMatchObject({
      code: "BAD_REQUEST",
      message: /already been assigned to a responder/i,
    });
  });
});
