export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  supabaseUrl: process.env.VITE_SUPABASE_URL ?? process.env.NEXT_PUBLIC_SUPABASE_URL ?? process.env.SUPABASE_URL ?? "https://efolfdoisgxptcbawejp.supabase.co",
  supabaseAnonKey: process.env.VITE_SUPABASE_ANON_KEY ?? process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY ?? "sb_publishable_EjeAtAGh9DXQLNvuW4axKA_fjBg5hxy",
  supabaseServiceRoleKey: process.env.SUPABASE_SERVICE_ROLE_KEY ?? "",
  adminEmail: process.env.ADMIN_EMAIL ?? "",
  adminContactNumber: process.env.ADMIN_CONTACT_NUMBER || process.env.VITE_ADMIN_CONTACT_NUMBER || "+91-361-2237011",
  n8nSosWebhookUrl: process.env.N8N_SOS_WEBHOOK_URL ?? "",
  n8nSosWebhookSecret: process.env.N8N_SOS_WEBHOOK_SECRET ?? process.env.N8N_WEBHOOK_SECRET ?? "",
  appBaseUrl: process.env.APP_URL ?? process.env.PUBLIC_APP_URL ?? process.env.RENDER_EXTERNAL_URL ?? "https://assam-rescue-platform.onrender.com",
  s3Bucket: process.env.AWS_S3_BUCKET ?? "",
  s3Region: process.env.AWS_S3_REGION ?? process.env.AWS_REGION ?? "us-east-1",
  s3AccessKeyId: process.env.AWS_ACCESS_KEY_ID ?? "",
  s3SecretAccessKey: process.env.AWS_SECRET_ACCESS_KEY ?? "",
  s3Endpoint: process.env.AWS_S3_ENDPOINT ?? "",
};
