import { Button } from "@/components/ui/button";
import { Ambulance, ArrowRight, HeartPulse, Radio, ShieldCheck, Siren, UsersRound } from "lucide-react";
import { publicRoleEntries } from "@/lib/publicRoleEntries";
import { useLocation } from "wouter";

export default function Home() {
  const [, setLocation] = useLocation();
  return <div className="min-h-screen overflow-hidden app-grid">
    <header className="sticky top-0 z-30 border-b border-[#dbece6]/80 bg-[#f7fbf9]/95 backdrop-blur">
      <div className="mx-auto flex max-w-7xl items-center justify-between gap-3 px-4 py-3 md:px-8">
        <button onClick={() => setLocation("/")} className="flex items-center gap-2.5 text-left"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-primary text-primary-foreground shadow-lg shadow-primary/20"><span className="font-mono text-sm font-bold">S</span></span><span><span className="block text-sm font-extrabold tracking-tight">sudo MakeItWork</span><span className="block font-mono text-[9px] uppercase tracking-[0.16em] text-muted-foreground">Assam emergency network</span></span></button>
        <Button onClick={() => setLocation("/emergency")} className="h-11 rounded-2xl bg-[#c94b45] px-4 font-extrabold text-white shadow-lg shadow-[#c94b45]/20 hover:bg-[#b9423d]"><Siren className="mr-2 h-4 w-4" /> SOS</Button>
      </div>
      <nav aria-label="Quick access" className="mx-auto grid max-w-7xl grid-cols-4 gap-2 px-4 pb-3 md:px-8">{publicRoleEntries.map(action => <button key={action.path} onClick={() => setLocation(action.path)} className={`flex min-h-16 flex-col items-center justify-center rounded-2xl px-2 text-center shadow-sm transition active:scale-[0.97] ${action.tone}`}><action.icon className="mb-1 h-4 w-4" /><span className="text-xs font-extrabold">{action.title}</span><span className="hidden text-[9px] opacity-70 sm:block">{action.caption}</span></button>)}</nav>
    </header>
    <main className="relative mx-auto max-w-7xl px-4 pb-12 pt-10 md:px-8 md:pt-16">
      <span className="river-line left-[-8%] top-36 h-5 w-[78%] opacity-55" /><span className="river-line right-[-15%] top-60 h-8 w-[72%] opacity-40" />
      <section className="relative grid items-center gap-10 lg:grid-cols-[1.05fr_0.95fr]"><div className="rise-in"><div className="inline-flex items-center gap-2 rounded-full border border-[#99ccbd] bg-[#edfbf5] px-3 py-1.5 font-mono text-[10px] font-medium uppercase tracking-[0.18em] text-[#277a69]"><span className="h-1.5 w-1.5 rounded-full bg-[#2fa77f]" /> Ready when every second matters</div><h1 className="mt-5 max-w-3xl text-5xl font-extrabold leading-[0.96] tracking-[-0.055em] text-[#173d37] sm:text-6xl md:text-7xl">One tap for help.<br/><span className="text-[#277b6b]">One team behind you.</span></h1><p className="mt-6 max-w-xl text-base leading-7 text-muted-foreground md:text-lg">A clear rescue path for people in danger, field responders, and emergency coordinators. No searching through menus when you need help.</p><div className="mt-8"><Button size="lg" onClick={() => setLocation("/emergency")} className="h-16 rounded-2xl bg-[#c94b45] px-7 text-lg font-extrabold text-white shadow-xl shadow-[#c94b45]/20 hover:bg-[#b9423d]"><Siren className="mr-3 h-6 w-6" /> Send SOS now</Button><p className="mt-3 text-xs font-semibold text-[#4e7169]">Your phone can save a report when offline and send it when you reconnect.</p></div></div>
        <section className="rise-in relative overflow-hidden rounded-[2.25rem] bg-[#174e46] p-6 text-white shadow-[0_32px_90px_-35px_rgb(20_78_70/0.8)] [animation-delay:100ms]"><div className="absolute -right-16 -top-20 h-48 w-48 rounded-full bg-[#48a690]/25 blur-3xl" /><div className="relative"><div className="flex items-center justify-between border-b border-white/15 pb-4"><span className="font-mono text-[10px] uppercase tracking-[0.22em] text-[#b1dbd1]">Choose the role that fits now</span><ShieldCheck className="h-5 w-5 text-[#9bdbc8]" /></div><div className="mt-5 grid gap-3"><RoleCard icon={Siren} title="I need help" copy="Report an SOS in a few visual steps." onClick={() => setLocation("/emergency")} accent="bg-[#fff0ee] text-[#c94b45]" /><RoleCard icon={UsersRound} title="I am a responder" copy="See assignments and set readiness." onClick={() => setLocation("/responder")} accent="bg-[#dff5ed] text-[#176154]" /><RoleCard icon={Radio} title="I coordinate rescue" copy="Open the command centre." onClick={() => setLocation("/command")} accent="bg-[#e3eefb] text-[#255c7d]" /></div></div></section>
      </section>
      <section className="mt-16 grid gap-4 md:grid-cols-3"><Feature icon={HeartPulse} title="Panic-mode SOS" text="Image-led choices, big controls, location first, and optional details only when you can provide them." /><Feature icon={Ambulance} title="Field-ready response" text="One secured workspace for missions, availability, alerts, and required status updates." /><Feature icon={Radio} title="Capacity in view" text="Coordinate SOS cases, relief shelters, hospitals, beds, and critical medical stock from command." /></section>
    </main>
  </div>;
}

function RoleCard({ icon: Icon, title, copy, accent, onClick }: { icon: typeof Siren; title: string; copy: string; accent: string; onClick: () => void }) { return <button onClick={onClick} className="group flex items-center gap-4 rounded-2xl bg-white/8 p-4 text-left transition hover:bg-white/12 active:scale-[0.99]"><span className={`grid h-11 w-11 place-items-center rounded-xl ${accent}`}><Icon className="h-5 w-5" /></span><span className="min-w-0 flex-1"><span className="block text-sm font-extrabold">{title}</span><span className="mt-0.5 block text-xs text-[#b9ddd5]">{copy}</span></span><ArrowRight className="h-4 w-4 text-[#b1dbd1] transition group-hover:translate-x-1" /></button>; }
function Feature({ icon: Icon, title, text }: { icon: typeof Siren; title: string; text: string }) { return <article className="rounded-2xl border bg-white/85 p-5 shadow-sm"><span className="grid h-10 w-10 place-items-center rounded-xl bg-secondary text-primary"><Icon className="h-5 w-5" /></span><h2 className="mt-5 font-extrabold tracking-tight">{title}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p></article>; }
