import LanguageSelector from "@/components/LanguageSelector";
import { VictimNavigation } from "@/pages/Home";
import { useAuth } from "@/_core/hooks/useAuth";
import { CircleHelp, ClipboardCheck, Headphones, Hospital, LogIn, ShieldCheck, UserRound, UsersRound } from "lucide-react";
import { startLogin } from "@/const";
import { useLocation } from "wouter";

export default function More() {
  const { user } = useAuth(); const [, setLocation] = useLocation();
  return <div className="victim-page min-h-screen bg-[#f6f8f7]"><main className="victim-main mx-auto min-h-screen max-w-lg bg-[#fcfdfd] px-5 pb-28 pt-6 md:my-6 md:min-h-[850px] md:rounded-[2.75rem] md:border"><header className="flex items-start justify-between"><div><p className="text-2xl font-black tracking-[-.06em]">More</p><p className="mt-1 text-[10px] font-bold text-[#6b8780]">Profile & support</p></div><LanguageSelector compact /></header><section className="mt-7 rounded-[1.8rem] bg-[#174e46] p-5 text-white"><div className="flex items-center gap-4"><span className="grid h-14 w-14 place-items-center rounded-2xl bg-white/10"><UserRound className="h-7 w-7 text-[#d3eee6]" /></span><div><p className="text-lg font-black">{user?.name || "Assam Safety Network"}</p><p className="mt-1 text-xs text-[#c2e2db]">Universal Access Active · All Portals Unlocked</p></div></div></section><section className="mt-5 grid gap-3"><Support icon={Headphones} title="Get support" copy="Help with an SOS, account, or accessibility." /><Support icon={ShieldCheck} title="Privacy and safety" copy="Your SOS details are shared only for emergency response." /><Support icon={CircleHelp} title="How the app works" copy="SOS works offline and is delivered once connectivity returns." /></section><button onClick={() => setLocation("/hospital/register")} className="mt-5 flex w-full items-center gap-4 rounded-[1.55rem] border border-[#c8ddef] bg-[#f5f9ff] p-4 text-left transition active:scale-[.99]"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-[#eaf2fb] text-[#255c7d]"><ClipboardCheck className="h-5 w-5" /></span><span><span className="block text-sm font-black text-[#234b77]">Hospital registration</span><span className="mt-1 block text-xs leading-5 text-[#58738f]">Hospitals can request verified staff access and publish live resource information.</span></span></button><section className="mt-5 rounded-[1.55rem] border border-[#d7e8e2] bg-[#f7fcfa] p-4"><p className="font-mono text-[10px] font-bold uppercase tracking-[.16em] text-[#277b6b]">Protected Operations App</p><p className="mt-1 text-sm font-black">For authorized response teams</p><div className="mt-3 grid grid-cols-3 gap-2"><AccessButton icon={ShieldCheck} label="Government" onClick={() => setLocation("/command")} /><AccessButton icon={Hospital} label="Medical" onClick={() => setLocation("/medical")} /><AccessButton icon={UsersRound} label="Rescuer" onClick={() => setLocation("/responder")} /></div></section></main><VictimNavigation current="more" /></div>;
}
function Support({ icon: Icon, title, copy }: { icon: typeof Headphones; title: string; copy: string }) { return <article className="flex items-center gap-4 rounded-[1.4rem] bg-white p-4 shadow-[0_12px_28px_rgba(22,60,53,.09)] ring-1 ring-black/[.035]"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#edf7f4] text-[#237563]"><Icon className="h-5 w-5" /></span><div><h2 className="text-sm font-black">{title}</h2><p className="mt-1 text-xs leading-5 text-[#6e8780]">{copy}</p></div></article>; }
function AccessButton({ icon: Icon, label, onClick }: { icon: typeof Hospital; label: string; onClick: () => void }) { return <button onClick={onClick} className="grid place-items-center gap-1 rounded-2xl bg-white px-2 py-3 text-[10px] font-black text-[#315e54] shadow-sm transition active:scale-95"><Icon className="h-4 w-4 text-[#277b6b]" />{label}</button>; }
