import type { Locale } from "./LanguageContext";

export const currentInterfaceTerms: Record<Locale, Record<string, string>> = {
  en: {},
  as: {
    "Sign in to activate": "সক্ৰিয় কৰিবলৈ ছাইন ইন কৰক", "Record voice note": "কণ্ঠ বাৰ্তা ৰেকৰ্ড কৰক", "Speak briefly if typing is difficult": "টাইপ কৰাটো কঠিন হ’লে সংক্ষিপ্তকৈ কওক", "Map preview": "মানচিত্ৰ পূৰ্বদৃশ্য", "Map centered on Assam": "অসমক কেন্দ্ৰ কৰি মানচিত্ৰ", "Local flood conditions": "স্থানীয় বান পৰিস্থিতি", "Rainfall now": "বৰ্তমান বৰষুণ", "Wind speed": "বতাহৰ গতি", "River level": "নদীৰ জলস্তৰ", "Unavailable": "উপলব্ধ নহয়", "No reading": "কোনো তথ্য নাই", "7-day trend": "৭ দিনৰ ধাৰা", "View graph": "গ্ৰাফ চাওক", "Weather forecast": "বতৰৰ পূৰ্বাভাস", "Your rescue flow": "আপোনাৰ উদ্ধাৰ প্ৰক্ৰিয়া", "Saved on this device": "এই ডিভাইচত সংৰক্ষিত", "No active SOS yet": "এতিয়াও কোনো সক্ৰিয় SOS নাই", "Go to SOS": "SOS লৈ যাওক", "Prepare, find support, act early": "প্ৰস্তুত হওক, সহায় বিচাৰক, আগতেই পদক্ষেপ লওক", "Profile & support": "প্ৰফাইল আৰু সহায়", "Your safety profile": "আপোনাৰ সুৰক্ষা প্ৰফাইল", "Government Command access": "চৰকাৰী কমাণ্ড প্ৰৱেশ", "Continue to Command sign-in": "কমান্ড ছাইন-ইনলৈ আগবাঢ়ক", "Return to Victim App": "পীড়িত এপলৈ উভতি যাওক",
  },
  hi: {
    "Sign in to activate": "सक्रिय करने के लिए साइन इन करें", "Record voice note": "वॉइस नोट रिकॉर्ड करें", "Speak briefly if typing is difficult": "टाइप करना कठिन हो तो संक्षेप में बोलें", "Map preview": "मानचित्र पूर्वावलोकन", "Map centered on Assam": "मानचित्र असम पर केंद्रित है", "Local flood conditions": "स्थानीय बाढ़ की स्थिति", "Rainfall now": "अभी वर्षा", "Wind speed": "हवा की गति", "River level": "नदी का जलस्तर", "Unavailable": "उपलब्ध नहीं", "No reading": "कोई रीडिंग नहीं", "7-day trend": "7-दिन का रुझान", "View graph": "ग्राफ देखें", "Weather forecast": "मौसम पूर्वानुमान", "Your rescue flow": "आपकी बचाव स्थिति", "Saved on this device": "इस डिवाइस पर सहेजा गया", "No active SOS yet": "अभी कोई सक्रिय SOS नहीं", "Go to SOS": "SOS पर जाएँ", "Prepare, find support, act early": "तैयार रहें, सहायता पाएँ, समय रहते कदम उठाएँ", "Profile & support": "प्रोफ़ाइल और सहायता", "Your safety profile": "आपकी सुरक्षा प्रोफ़ाइल", "Government Command access": "सरकारी कमांड पहुंच", "Continue to Command sign-in": "कमांड साइन-इन जारी रखें", "Return to Victim App": "पीड़ित ऐप पर लौटें",
  },
  bn: {
    "Sign in to activate": "সক্রিয় করতে সাইন ইন করুন", "Record voice note": "ভয়েস নোট রেকর্ড করুন", "Speak briefly if typing is difficult": "টাইপ করা কঠিন হলে সংক্ষেপে বলুন", "Map preview": "মানচিত্র প্রিভিউ", "Map centered on Assam": "মানচিত্র অসমে কেন্দ্রীভূত", "Local flood conditions": "স্থানীয় বন্যা পরিস্থিতি", "Rainfall now": "এখন বৃষ্টিপাত", "Wind speed": "বাতাসের গতি", "River level": "নদীর জলস্তর", "Unavailable": "অনুপলব্ধ", "No reading": "কোনও তথ্য নেই", "7-day trend": "৭ দিনের প্রবণতা", "View graph": "গ্রাফ দেখুন", "Weather forecast": "আবহাওয়ার পূর্বাভাস", "Your rescue flow": "আপনার উদ্ধার অগ্রগতি", "Saved on this device": "এই ডিভাইসে সংরক্ষিত", "No active SOS yet": "এখনও কোনও সক্রিয় SOS নেই", "Go to SOS": "SOS-এ যান", "Prepare, find support, act early": "প্রস্তুত থাকুন, সহায়তা নিন, আগে পদক্ষেপ নিন", "Profile & support": "প্রোফাইল ও সহায়তা", "Your safety profile": "আপনার সুরক্ষা প্রোফাইল", "Government Command access": "সরকারি কমান্ড প্রবেশ", "Continue to Command sign-in": "কমান্ড সাইন-ইন চালিয়ে যান", "Return to Victim App": "ভুক্তভোগী অ্যাপে ফিরুন",
  },
  or: {
    "Sign in to activate": "ସକ୍ରିୟ କରିବା ପାଇଁ ସାଇନ୍ ଇନ୍ କରନ୍ତୁ", "Record voice note": "ଭଏସ୍ ନୋଟ୍ ରେକର୍ଡ କରନ୍ତୁ", "Speak briefly if typing is difficult": "ଟାଇପ୍ କରିବା କଷ୍ଟକର ହେଲେ ସଂକ୍ଷେପରେ କୁହନ୍ତୁ", "Map preview": "ମାନଚିତ୍ର ପୂର୍ବଦୃଶ୍ୟ", "Map centered on Assam": "ମାନଚିତ୍ର ଆସାମ ଉପରେ କେନ୍ଦ୍ରିତ", "Local flood conditions": "ସ୍ଥାନୀୟ ବନ୍ୟା ପରିସ୍ଥିତି", "Rainfall now": "ବର୍ତ୍ତମାନ ବର୍ଷା", "Wind speed": "ପବନ ବେଗ", "River level": "ନଦୀ ଜଳସ୍ତର", "Unavailable": "ଉପଲବ୍ଧ ନାହିଁ", "No reading": "କୌଣସି ତଥ୍ୟ ନାହିଁ", "7-day trend": "୭ ଦିନର ପ୍ରବଣତା", "View graph": "ଗ୍ରାଫ୍ ଦେଖନ୍ତୁ", "Weather forecast": "ପାଣିପାଗ ପୂର୍ବାନୁମାନ", "Your rescue flow": "ଆପଣଙ୍କ ଉଦ୍ଧାର ସ୍ଥିତି", "Saved on this device": "ଏହି ଡିଭାଇସରେ ସଂରକ୍ଷିତ", "No active SOS yet": "ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି ସକ୍ରିୟ SOS ନାହିଁ", "Go to SOS": "SOS କୁ ଯାଆନ୍ତୁ", "Prepare, find support, act early": "ପ୍ରସ୍ତୁତ ରୁହନ୍ତୁ, ସହାୟତା ପାଆନ୍ତୁ, ଶୀଘ୍ର ପଦକ୍ଷେପ ନିଅନ୍ତୁ", "Profile & support": "ପ୍ରୋଫାଇଲ୍ ଓ ସହାୟତା", "Your safety profile": "ଆପଣଙ୍କ ସୁରକ୍ଷା ପ୍ରୋଫାଇଲ୍", "Government Command access": "ସରକାରୀ କମାଣ୍ଡ ପ୍ରବେଶ", "Continue to Command sign-in": "କମାଣ୍ଡ ସାଇନ୍ ଇନ୍ ଜାରି ରଖନ୍ତୁ", "Return to Victim App": "ପୀଡ଼ିତ ଆପକୁ ଫେରନ୍ତୁ",
  },
  mr: {
    "Sign in to activate": "सक्रिय करण्यासाठी साइन इन करा", "Record voice note": "व्हॉइस नोट रेकॉर्ड करा", "Speak briefly if typing is difficult": "टाइप करणे कठीण असल्यास थोडक्यात बोला", "Map preview": "नकाशा पूर्वदृश्य", "Map centered on Assam": "नकाशा आसामवर केंद्रित आहे", "Local flood conditions": "स्थानिक पूरस्थिती", "Rainfall now": "सध्याचा पाऊस", "Wind speed": "वाऱ्याचा वेग", "River level": "नदीची पातळी", "Unavailable": "उपलब्ध नाही", "No reading": "कोणतीही नोंद नाही", "7-day trend": "७ दिवसांचा कल", "View graph": "आलेख पाहा", "Weather forecast": "हवामान अंदाज", "Your rescue flow": "तुमची बचाव स्थिती", "Saved on this device": "या डिव्हाइसवर जतन केले", "No active SOS yet": "अजून सक्रिय SOS नाही", "Go to SOS": "SOS कडे जा", "Prepare, find support, act early": "तयार रहा, मदत मिळवा, लवकर पाऊल उचला", "Profile & support": "प्रोफाइल आणि मदत", "Your safety profile": "तुमची सुरक्षा प्रोफाइल", "Government Command access": "सरकारी कमांड प्रवेश", "Continue to Command sign-in": "कमांड साइन इन सुरू ठेवा", "Return to Victim App": "पीडित ॲपवर परत जा",
  },
  gu: {
    "Sign in to activate": "સક્રિય કરવા માટે સાઇન ઇન કરો", "Record voice note": "વૉઇસ નોટ રેકોર્ડ કરો", "Speak briefly if typing is difficult": "ટાઇપ કરવું મુશ્કેલ હોય તો ટૂંકમાં બોલો", "Map preview": "નકશાનું પૂર્વદર્શન", "Map centered on Assam": "નકશો આસામ પર કેન્દ્રિત છે", "Local flood conditions": "સ્થાનિક પૂર સ્થિતિ", "Rainfall now": "હાલનો વરસાદ", "Wind speed": "પવનની ગતિ", "River level": "નદીનું જળસ્તર", "Unavailable": "ઉપલબ્ધ નથી", "No reading": "કોઈ માપ નથી", "7-day trend": "7 દિવસનો વલણ", "View graph": "ગ્રાફ જુઓ", "Weather forecast": "હવામાન આગાહી", "Your rescue flow": "તમારી બચાવ સ્થિતિ", "Saved on this device": "આ ઉપકરણમાં સાચવેલ", "No active SOS yet": "હજુ કોઈ સક્રિય SOS નથી", "Go to SOS": "SOS પર જાઓ", "Prepare, find support, act early": "તૈયાર રહો, મદદ મેળવો, વહેલા પગલા લો", "Profile & support": "પ્રોફાઇલ અને સહાય", "Your safety profile": "તમારી સુરક્ષા પ્રોફાઇલ", "Government Command access": "સરકારી કમાન્ડ પ્રવેશ", "Continue to Command sign-in": "કમાન્ડ સાઇન ઇન ચાલુ રાખો", "Return to Victim App": "પીડિત એપ પર પાછા જાઓ",
  },
  ta: {
    "Sign in to activate": "செயல்படுத்த உள்நுழையவும்", "Record voice note": "குரல் குறிப்பைப் பதிவு செய்யவும்", "Speak briefly if typing is difficult": "தட்டச்சு கடினமாக இருந்தால் சுருக்கமாகப் பேசவும்", "Map preview": "வரைபட முன்னோட்டம்", "Map centered on Assam": "வரைபடம் அசாமை மையமாகக் கொண்டுள்ளது", "Local flood conditions": "உள்ளூர் வெள்ள நிலவரம்", "Rainfall now": "தற்போதைய மழை", "Wind speed": "காற்றின் வேகம்", "River level": "ஆற்று நீர்மட்டம்", "Unavailable": "கிடைக்கவில்லை", "No reading": "தரவு இல்லை", "7-day trend": "7 நாள் போக்கு", "View graph": "வரைபடத்தைப் பார்க்கவும்", "Weather forecast": "வானிலை முன்னறிவிப்பு", "Your rescue flow": "உங்கள் மீட்பு நிலை", "Saved on this device": "இந்தச் சாதனத்தில் சேமிக்கப்பட்டது", "No active SOS yet": "இதுவரை செயலில் SOS இல்லை", "Go to SOS": "SOS-க்கு செல்லவும்", "Prepare, find support, act early": "தயாராக இருங்கள், உதவி பெறுங்கள், முன்கூட்டியே செயல்படுங்கள்", "Profile & support": "சுயவிவரம் மற்றும் உதவி", "Your safety profile": "உங்கள் பாதுகாப்பு சுயவிவரம்", "Government Command access": "அரசு கட்டளை அணுகல்", "Continue to Command sign-in": "கட்டளை உள்நுழைவைத் தொடரவும்", "Return to Victim App": "பாதிக்கப்பட்டோர் செயலிக்கு திரும்பவும்",
  },
  te: {
    "Sign in to activate": "సక్రియం చేయడానికి సైన్ ఇన్ చేయండి", "Record voice note": "వాయిస్ నోట్ రికార్డ్ చేయండి", "Speak briefly if typing is difficult": "టైప్ చేయడం కష్టమైతే క్లుప్తంగా మాట్లాడండి", "Map preview": "మ్యాప్ ప్రివ్యూ", "Map centered on Assam": "మ్యాప్ అస్సాంపై కేంద్రీకృతమై ఉంది", "Local flood conditions": "స్థానిక వరద పరిస్థితులు", "Rainfall now": "ప్రస్తుత వర్షపాతం", "Wind speed": "గాలి వేగం", "River level": "నది నీటి మట్టం", "Unavailable": "అందుబాటులో లేదు", "No reading": "డేటా లేదు", "7-day trend": "7 రోజుల ధోరణి", "View graph": "గ్రాఫ్ చూడండి", "Weather forecast": "వాతావరణ అంచనా", "Your rescue flow": "మీ రక్షణ స్థితి", "Saved on this device": "ఈ పరికరంలో సేవ్ చేయబడింది", "No active SOS yet": "ఇంకా సక్రియ SOS లేదు", "Go to SOS": "SOS కు వెళ్లండి", "Prepare, find support, act early": "సిద్ధంగా ఉండండి, సహాయం పొందండి, ముందుగానే చర్య తీసుకోండి", "Profile & support": "ప్రొఫైల్ మరియు సహాయం", "Your safety profile": "మీ భద్రత ప్రొఫైల్", "Government Command access": "ప్రభుత్వ కమాండ్ ప్రవేశం", "Continue to Command sign-in": "కమాండ్ సైన్ ఇన్ కొనసాగించండి", "Return to Victim App": "బాధితుల యాప్‌కు తిరిగి వెళ్ళండి",
  },
  kn: {
    "Sign in to activate": "ಸಕ್ರಿಯಗೊಳಿಸಲು ಸೈನ್ ಇನ್ ಮಾಡಿ", "Record voice note": "ಧ್ವನಿ ಟಿಪ್ಪಣಿ ದಾಖಲಿಸಿ", "Speak briefly if typing is difficult": "ಟೈಪ್ ಮಾಡುವುದು ಕಷ್ಟವಾದರೆ ಸಂಕ್ಷಿಪ್ತವಾಗಿ ಮಾತನಾಡಿ", "Map preview": "ನಕ್ಷೆ ಪೂರ್ವವೀಕ್ಷಣೆ", "Map centered on Assam": "ನಕ್ಷೆ ಅಸ್ಸಾಂನಲ್ಲಿ ಕೇಂದ್ರೀಕೃತವಾಗಿದೆ", "Local flood conditions": "ಸ್ಥಳೀಯ ಪ್ರವಾಹ ಪರಿಸ್ಥಿತಿಗಳು", "Rainfall now": "ಪ್ರಸ್ತುತ ಮಳೆ", "Wind speed": "ಗಾಳಿಯ ವೇಗ", "River level": "ನದಿಯ ನೀರಿನ ಮಟ್ಟ", "Unavailable": "ಲಭ್ಯವಿಲ್ಲ", "No reading": "ಯಾವುದೇ ಮಾಹಿತಿ ಇಲ್ಲ", "7-day trend": "7 ದಿನಗಳ ಪ್ರವೃತ್ತಿ", "View graph": "ಗ್ರಾಫ್ ನೋಡಿ", "Weather forecast": "ಹವಾಮಾನ ಮುನ್ಸೂಚನೆ", "Your rescue flow": "ನಿಮ್ಮ ರಕ್ಷಣಾ ಸ್ಥಿತಿ", "Saved on this device": "ಈ ಸಾಧನದಲ್ಲಿ ಉಳಿಸಲಾಗಿದೆ", "No active SOS yet": "ಇನ್ನೂ ಸಕ್ರಿಯ SOS ಇಲ್ಲ", "Go to SOS": "SOS ಗೆ ಹೋಗಿ", "Prepare, find support, act early": "ಸಿದ್ಧರಿರಿ, ಸಹಾಯ ಪಡೆಯಿರಿ, ಬೇಗ ಕ್ರಮ ತೆಗೆದುಕೊಳ್ಳಿ", "Profile & support": "ಪ್ರೊಫೈಲ್ ಮತ್ತು ಸಹಾಯ", "Your safety profile": "ನಿಮ್ಮ ಸುರಕ್ಷತಾ ಪ್ರೊಫೈಲ್", "Government Command access": "ಸರ್ಕಾರಿ ಕಮಾಂಡ್ ಪ್ರವೇಶ", "Continue to Command sign-in": "ಕಮಾಂಡ್ ಸೈನ್ ಇನ್ ಮುಂದುವರಿಸಿ", "Return to Victim App": "ಬಾಧಿತ ಆಪ್‌ಗೆ ಹಿಂತಿರುಗಿ",
  },
};

const sharedInterfaceTerms: Record<Locale, Record<string, string>> = {
  en: {},
  as: { "Connected": "সংযুক্ত", "Track": "খবৰ লওক", "Safety": "সুৰক্ষা", "More": "অধিক", "Switch to dark theme": "ডাৰ্ক থীমলৈ সলনি কৰক", "Switch to light theme": "লাইট থীমলৈ সলনি কৰক" },
  hi: { "Connected": "कनेक्टेड", "Track": "स्थिति देखें", "Safety": "सुरक्षा", "More": "और", "Switch to dark theme": "डार्क थीम में बदलें", "Switch to light theme": "लाइट थीम में बदलें" },
  bn: { "Connected": "সংযুক্ত", "Track": "ট্র্যাক", "Safety": "নিরাপত্তা", "More": "আরও", "Switch to dark theme": "ডার্ক থিমে বদলান", "Switch to light theme": "লাইট থিমে বদলান" },
  or: { "Connected": "ସଂଯୁକ୍ତ", "Track": "ଟ୍ରାକ୍", "Safety": "ସୁରକ୍ଷା", "More": "ଅଧିକ", "Switch to dark theme": "ଡାର୍କ ଥିମକୁ ବଦଳାନ୍ତୁ", "Switch to light theme": "ଲାଇଟ ଥିମକୁ ବଦଳାନ୍ତୁ" },
  mr: { "Connected": "कनेक्टेड", "Track": "मागोवा", "Safety": "सुरक्षा", "More": "अधिक", "Switch to dark theme": "डार्क थीमवर बदला", "Switch to light theme": "लाइट थीमवर बदला" },
  gu: { "Connected": "જોડાયેલ", "Track": "ટ્રૅક", "Safety": "સુરક્ષા", "More": "વધુ", "Switch to dark theme": "ડાર્ક થીમ પર બદલો", "Switch to light theme": "લાઇટ થીમ પર બદલો" },
  ta: { "Connected": "இணைக்கப்பட்டுள்ளது", "Track": "கண்காணிப்பு", "Safety": "பாதுகாப்பு", "More": "மேலும்", "Switch to dark theme": "இருண்ட தோற்றத்திற்கு மாறவும்", "Switch to light theme": "ஒளி தோற்றத்திற்கு மாறவும்" },
  te: { "Connected": "కనెక్ట్ అయింది", "Track": "ట్రాక్", "Safety": "భద్రత", "More": "మరిన్ని", "Switch to dark theme": "డార్క్ థీమ్‌కు మార్చండి", "Switch to light theme": "లైట్ థీమ్‌కు మార్చండి" },
  kn: { "Connected": "ಸಂಪರ್ಕಗೊಂಡಿದೆ", "Track": "ಟ್ರ್ಯಾಕ್", "Safety": "ಸುರಕ್ಷತೆ", "More": "ಇನ್ನಷ್ಟು", "Switch to dark theme": "ಡಾರ್ಕ್ ಥೀಮ್‌ಗೆ ಬದಲಿಸಿ", "Switch to light theme": "ಲೈಟ್ ಥೀಮ್‌ಗೆ ಬದಲಿಸಿ" },
};

for (const { code } of [{ code: "en" }, { code: "as" }, { code: "hi" }, { code: "bn" }, { code: "or" }, { code: "mr" }, { code: "gu" }, { code: "ta" }, { code: "te" }, { code: "kn" }] as Array<{ code: Locale }>) {
  Object.assign(currentInterfaceTerms[code], sharedInterfaceTerms[code]);
}
