import type { Locale } from "./LanguageContext";

export const currentInterfaceTerms: Record<Locale, Record<string, string>> = {
  en: {},
  as: {
    "Sign in to activate": "সক্ৰিয় কৰিবলৈ ছাইন ইন কৰক",
    "Record voice note": "কণ্ঠ বাৰ্তা ৰেকৰ্ড কৰক",
    "Speak briefly if typing is difficult": "টাইপ কৰাটো কঠিন হ’লে সংক্ষিপ্তকৈ কওক",
    "Map preview": "মানচিত্ৰ পূৰ্বদৃশ্য",
    "Map centered on Assam": "অসমক কেন্দ্ৰ কৰি মানচিত্ৰ",
    "Local flood conditions": "স্থানীয় বান পৰিস্থিতি",
    "Rainfall now": "বৰ্তমান বৰষুণ",
    "Wind speed": "বতাহৰ গতি",
    "River level": "নদীৰ জলস্তৰ",
    "Unavailable": "উপলব্ধ নহয়",
    "No reading": "কোনো তথ্য নাই",
    "7-day trend": "৭ দিনৰ ধাৰা",
    "View graph": "গ্ৰাফ চাওক",
    "Weather forecast": "বতৰৰ পূৰ্বাভাস",
    "Your rescue flow": "আপোনাৰ উদ্ধাৰ প্ৰক্ৰিয়া",
    "Saved on this device": "এই ডিভাইচত সংৰক্ষিত",
    "No active SOS yet": "এতিয়াও কোনো সক্ৰিয় SOS নাই",
    "Go to SOS": "SOS লৈ যাওক",
    "Prepare, find support, act early": "প্ৰস্তুত হওক, সহায় বিচাৰক, আগতেই পদক্ষেপ লওক",
    "Profile & support": "প্ৰফাইল আৰু সহায়",
    "Your safety profile": "আপোনাৰ সুৰক্ষা প্ৰফাইল",
    "Government Command access": "চৰকাৰী কমাণ্ড প্ৰৱেশ",
    "Continue to Command sign-in": "কমান্ড ছাইন-ইনলৈ আগবাঢ়ক",
    "Return to Victim App": "পীড়িত এপলৈ উভতি যাওক",
    "Safety": "সুৰক্ষা",
    "Nearby hospital information": "ওচৰৰ চিকিৎসালয়ৰ তথ্য",
    "Stay safe, stay informed": "নিৰাপদে থাকক, অৱগত থাকক",
    "Find verified nearby medical care. For immediate danger, send an SOS now.": "সত্যাপন কৰা ওচৰৰ চিকিৎসা সেৱা বিচাৰক। জৰুৰী বিপদৰ বাবে এতিয়াই SOS পঠিয়াওক।",
    "Call 112": "১১২ লৈ কল কৰক",
    "Rapid SOS": "দ্ৰুত SOS",
    "Verified medical care": "সত্যাপিত চিকিৎসা সেৱা",
    "Nearby hospitals": "ওচৰৰ চিকিৎসালয়সমূহ",
    "Nearest verified hospital shown first": "ওচৰৰ সত্যাপন কৰা চিকিৎসালয় প্ৰথমে দেখুওৱা হৈছে",
    "Finding hospitals near you…": "আপোনাৰ ওচৰৰ চিকিৎসালয় বিচৰা হৈছে…",
    "Use location to sort hospitals by distance": "দূৰত্ব অনুসৰি চিকিৎসালয় সজাবলৈ অৱস্থান ব্যৱহাৰ কৰক",
    "Refresh nearby hospitals": "ওচৰৰ চিকিৎসালয়সমূহ সতেজ কৰক",
    "Get directions": "দিশ নিৰ্দেশনা লওক",
    "Open": "খোলা আছে",
    "Beds ready": "বিচনা উপলব্ধ",
    "ICU ready": "ICU সাজু",
    "of": "ৰ ভিতৰত",
    "total": "মুঠ",
    "Food": "খাদ্য",
    "Medicine": "ঔষধ",
    "Water": "পানী",
    "Power": "বিদ্যুত",
    "Updated": "আপডেট কৰা হ’ল",
    "Call": "কল কৰক",
    "No call number": "কোনো ফোন নম্বৰ নাই",
    "Loading verified hospitals…": "সত্যাপিত চিকিৎসালয়সমূহ লোড হৈছে…",
    "No verified hospital listed nearby": "ওচৰত কোনো সত্যাপন কৰা চিকিৎসালয় তালিকাভুক্ত নাই",
    "Hospital information appears here after a hospital is verified and staff publish its current capacity.": "চিকিৎসালয় সত্যাপন কৰাৰ পিছত আৰু কৰ্মচাৰীয়ে ক্ষমতা প্ৰকাশ কৰিলে তথ্য ইয়াত দেখা যাব।",
    "Flood safety now": "বানপানী সুৰক্ষা",
    "Move higher": "উচ্চ স্থানলৈ যাওক",
    "Leave low ground before water rises.": "পানী বঢ়াৰ আগতেই নিম্নভূমি ত্যাগ কৰক।",
    "Avoid water": "পানী পৰিহাৰ কৰক",
    "Never walk or drive through moving water.": "বৈ থকা পানীৰ মাজেৰে কেতিয়াও খোজ বা গাড়ী নচলাব।",
    "Keep contact": "যোগাযোগ ৰাখক",
    "Charge your phone and keep emergency numbers ready.": "ফোন চাৰ্জ কৰক আৰু জৰুৰী নম্বৰসমূহ সাজু ৰাখক।",
    "Checking conditions": "পৰিস্থিতি পৰীক্ষা কৰা হৈছে",
    "High rainfall risk": "প্ৰচণ্ড বৰষুণৰ আশংকা",
    "Elevated rainfall risk": "অধিক বৰষুণৰ আশংকা",
    "Current model conditions": "বৰ্তমান মডেলৰ পৰিস্থিতি",
    "Weather source unavailable": "বতৰৰ উৎস উপলব্ধ নহয়",
    "chance of rain today": "আজি বৰষুণৰ সম্ভাৱনা",
    "forecast": "পূৰ্বাভাস",
    "Avoid low-lying routes and move early if local authorities advise.": "নিম্ন অঞ্চলৰ পথ পৰিহাৰ কৰক আৰু কৰ্তৃপক্ষই পৰামৰ্শ দিলে সোনকালে স্থানান্তৰিত হওক।",
    "Keep monitoring local authority alerts before travelling.": "ভ্ৰমণৰ পূৰ্বে স্থানীয় কৰ্তৃপক্ষৰ সতৰ্কবাণীসমূহ লক্ষ্য কৰক।",
    "Live weather information is temporarily unavailable. Follow official local authority warnings and do not rely on this screen alone.": "লাইভ বতৰ তথ্য সাময়িকভাৱে অনুপলব্ধ। চৰকাৰী নিৰ্দেশনা মানি চলক।",
    "Official river gauge": "চৰকাৰী নদী গেজ",
    "rising": "বৃদ্ধি পাইছে",
    "falling": "হ্ৰাস পাইছে",
    "steady": "স্থিৰ",
    "observed": "পৰ্যবেক্ষণ কৰা হৈছে",
    "Official source": "চৰকাৰী উৎস",
    "Weather model loading": "বতৰ মডেল লোড হৈ আছে",
    "Official river-gauge data is temporarily unavailable.": "চৰকাৰী নদীৰ তথ্য সাময়িকভাৱে অনুপলব্ধ।",
    "Local alert": "স্থানীয় সতৰ্কবাণী",
    "loading": "লোড হৈ আছে",
    "Profile & Operations Gateways": "প্ৰফাইল আৰু কাৰ্যকৰী প্ৰৱেশদ্বাৰ",
    "Assam Safety Network": "অসম সুৰক্ষা নেটৱৰ্ক",
    "Citizen Account": "নাগৰিক একাউণ্ট",
    "Tap to customize safety profile & emergency contacts": "সুৰক্ষা প্ৰফাইল আৰু জৰুৰী যোগাযোগ কাস্টমাইজ কৰিবলৈ টেপ কৰক",
    "Hospital registration": "চিকিৎসালয় পঞ্জীয়ন",
    "Hospitals can request verified staff access and publish live resource information.": "চিকিৎসালয়ে কৰ্মচাৰী প্ৰৱেশ অনুৰোধ কৰি লাইভ সম্পদ তথ্য প্ৰকাশ কৰিব পাৰে।",
    "Protected Operations App": "সুৰক্ষিত কাৰ্যকৰী এপ",
    "For authorized response teams": "অনুমোদিত সঁহাৰি দলৰ বাবে",
    "Government": "চৰকাৰী",
    "Medical": "চিকিৎসা",
    "Rescuer": "উদ্ধাৰকৰ্মী",
    "When you activate SOS, your rescue flow will remain here—even after refresh.": "আপুনি SOS সক্ৰিয় কৰিলে উদ্ধাৰ প্ৰক্ৰিয়া ইয়াত থাকিব—ৰिफ্ৰেছ কৰাৰ পিছতো।",
    "Updating rescue flow": "উদ্ধাৰ প্ৰক্ৰিয়া আপডেট হৈছে",
    "Live rescue flow": "লাইভ উদ্ধাৰ প্ৰক্ৰিয়া",
    "Tracking no.": "ট্ৰেকিং নম্বৰ",
    "Responder details will appear automatically after Command assigns the mission.": "কমান্ডে দায়িত্ব দিয়াৰ পিছত উদ্ধাৰকৰ্মীৰ বিৱৰণ স্বয়ংক্ৰিয়ভাৱে দেখা যাব।",
    "Only your authorized account can add details or message the rescue team.": "কেৱল অনুমোদিত একাউণ্টেহে বিৱৰণ যোগ কৰিব বা বাৰ্তা পঠিয়াব পাৰে।",
    "Sign in with the reporting account to add details or message the rescue team.": "বিৱৰণ যোগ বা বাৰ্তা পঠিয়াবলৈ ৰিপৰ্ট কৰা একাউণ্টেৰে ছাইন ইন কৰক।",
    "SOS received": "SOS পোৱা গৈছে",
    "Command is reviewing your location": "কমান্ডে আপোনাৰ অৱস্থান পৰ্যালোচনা কৰিছে",
    "Rescuer assigned": "উদ্ধাৰকৰ্মী নিযুক্ত কৰা হ’ল",
    "Your responder’s profile and live updates appear here": "আপোনাৰ উদ্ধাৰকৰ্মীৰ প্ৰফাইল আৰু লাইভ আপডেট ইয়াত দেখা যাব",
    "Rescue completed": "উদ্ধাৰ কাৰ্য সম্পন্ন হ’ল",
    "This rescue flow is recorded on this device": "এই উদ্ধাৰ প্ৰক্ৰিয়া এই ডিভাইচত সংৰক্ষণ কৰা হৈছে",
    "Add more details": "অধিক বিৱৰণ যোগ কৰক",
    "People with you, help needed, and useful updates for responders.": "লগত থকা লোক, প্ৰয়োজনীয় সহায় আৰু উদ্ধাৰকৰ্মীৰ বাবে উপযোগী তথ্য।",
    "Sahayak AI": "সহায়ক AI",
    "Ask Sahayak AI": "সহায়ক AI ক সোধক",
    "Type your question...": "আপোনাৰ প্ৰশ্ন লিখক...",
    "Send": "পঠিয়াওক",
    "Close": "বন্ধ কৰক",
    "Emergency Contacts": "জৰুৰী যোগাযোগসমূহ",
    "Edit Profile": "প্ৰফাইল সম্পাদনা কৰক",
    "Save Changes": "পৰিৱৰ্তন সাঁচক",
    "Donations": "দান-বৰঙণি",
    "Donate Now": "এতিয়াই দান কৰক",
  },
  hi: {
    "Sign in to activate": "सक्रिय करने के लिए साइन इन करें",
    "Record voice note": "वॉइस नोट रिकॉर्ड करें",
    "Speak briefly if typing is difficult": "टाइप करना कठिन हो तो संक्षेप में बोलें",
    "Map preview": "मानचित्र पूर्वावलोकन",
    "Map centered on Assam": "मानचित्र असम पर केंद्रित है",
    "Local flood conditions": "स्थानीय बाढ़ की स्थिति",
    "Rainfall now": "अभी वर्षा",
    "Wind speed": "हवा की गति",
    "River level": "नदी का जलस्तर",
    "Unavailable": "उपलब्ध नहीं",
    "No reading": "कोई रीडिंग नहीं",
    "7-day trend": "7-दिन का रुझान",
    "View graph": "ग्राफ देखें",
    "Weather forecast": "मौसम पूर्वानुमान",
    "Your rescue flow": "आपकी बचाव स्थिति",
    "Saved on this device": "इस डिवाइस पर सहेजा गया",
    "No active SOS yet": "अभी कोई सक्रिय SOS नहीं",
    "Go to SOS": "SOS पर जाएँ",
    "Prepare, find support, act early": "तैयार रहें, सहायता पाएँ, समय रहते कदम उठाएँ",
    "Profile & support": "प्रोफ़ाइल और सहायता",
    "Your safety profile": "आपकी सुरक्षा प्रोफ़ाइल",
    "Government Command access": "सरकारी कमांड पहुंच",
    "Continue to Command sign-in": "कमांड साइन-इन जारी रखें",
    "Return to Victim App": "पीड़ित ऐप पर लौटें",
    "Safety": "सुरक्षा",
    "Nearby hospital information": "आसपास के अस्पताल की जानकारी",
    "Stay safe, stay informed": "सुरक्षित रहें, जागरूक रहें",
    "Find verified nearby medical care. For immediate danger, send an SOS now.": "सत्यापित नजदीकी चिकित्सा देखभाल खोजें। तत्काल खतरे के लिए, अभी SOS भेजें।",
    "Call 112": "112 पर कॉल करें",
    "Rapid SOS": "त्वरित SOS",
    "Verified medical care": "सत्यापित चिकित्सा देखभाल",
    "Nearby hospitals": "आसपास के अस्पताल",
    "Nearest verified hospital shown first": "निकटतम सत्यापित अस्पताल पहले दिखाया गया है",
    "Finding hospitals near you…": "आपके आस-पास अस्पताल खोजा जा रहा है…",
    "Use location to sort hospitals by distance": "दूरी के अनुसार अस्पताल छांटने के लिए स्थान का उपयोग करें",
    "Refresh nearby hospitals": "आसपास के अस्पतालों को रिफ्रेश करें",
    "Get directions": "रास्ता प्राप्त करें",
    "Open": "खुला है",
    "Beds ready": "बेड उपलब्ध",
    "ICU ready": "ICU उपलब्ध",
    "of": "में से",
    "total": "कुल",
    "Food": "भोजन",
    "Medicine": "दवा",
    "Water": "पानी",
    "Power": "बिजली",
    "Updated": "अपडेट किया गया",
    "Call": "कॉल करें",
    "No call number": "कोई कॉल नंबर नहीं",
    "Loading verified hospitals…": "सत्यापित अस्पताल लोड हो रहे हैं…",
    "No verified hospital listed nearby": "आसपास कोई सत्यापित अस्पताल सूचीबद्ध नहीं है",
    "Hospital information appears here after a hospital is verified and staff publish its current capacity.": "अस्पताल के सत्यापित होने और कर्मचारियों द्वारा इसकी वर्तमान क्षमता प्रकाशित करने के बाद अस्पताल की जानकारी यहाँ दिखाई देती है।",
    "Flood safety now": "बाढ़ से सुरक्षा",
    "Move higher": "ऊंचे स्थान पर जाएं",
    "Leave low ground before water rises.": "पानी का स्तर बढ़ने से पहले निचले इलाके को छोड़ दें।",
    "Avoid water": "पानी से बचें",
    "Never walk or drive through moving water.": "बहते पानी में कभी न चलें और न ही गाड़ी चलाएं।",
    "Keep contact": "संपर्क बनाए रखें",
    "Charge your phone and keep emergency numbers ready.": "अपना फोन चार्ज करें और आपातकालीन नंबर तैयार रखें।",
    "Checking conditions": "स्थितियों की जाँच की जा रही है",
    "High rainfall risk": "भारी वर्षा का जोखिम",
    "Elevated rainfall risk": "अधिक वर्षा का जोखिम",
    "Current model conditions": "वर्तमान मॉडल की स्थिति",
    "Weather source unavailable": "मौसम स्रोत अनुपलब्ध",
    "chance of rain today": "आज बारिश की संभावना",
    "forecast": "पूर्वानुमान",
    "Avoid low-lying routes and move early if local authorities advise.": "निचले मार्गों से बचें और यदि स्थानीय अधिकारी सलाह दें तो जल्दी चले जाएं।",
    "Keep monitoring local authority alerts before travelling.": "यात्रा करने से पहले स्थानीय अधिकारियों के अलर्ट पर नजर रखें।",
    "Live weather information is temporarily unavailable. Follow official local authority warnings and do not rely on this screen alone.": "लाइव मौसम की जानकारी अस्थायी रूप से अनुपलब्ध है। आधिकारिक स्थानीय चेतावनियों का पालन करें और केवल इस स्क्रीन पर निर्भर न रहें।",
    "Official river gauge": "आधिकारिक नदी गेज",
    "rising": "बढ़ रहा है",
    "falling": "घट रहा है",
    "steady": "स्थिर",
    "observed": "देखा गया",
    "Official source": "आधिकारिक स्रोत",
    "Weather model loading": "मौसम मॉडल लोड हो रहा है",
    "Official river-gauge data is temporarily unavailable.": "आधिकारिक नदी-गेज डेटा अस्थायी रूप से अनुपलब्ध है।",
    "Local alert": "स्थानीय अलर्ट",
    "loading": "लोड हो रहा है",
    "Profile & Operations Gateways": "प्रोफ़ाइल और संचालन गेटवे",
    "Assam Safety Network": "असम सुरक्षा नेटवर्क",
    "Citizen Account": "नागरिक खाता",
    "Tap to customize safety profile & emergency contacts": "सुरक्षा प्रोफ़ाइल और आपातकालीन संपर्कों को अनुकूलित करने के लिए टैप करें",
    "Hospital registration": "अस्पताल पंजीकरण",
    "Hospitals can request verified staff access and publish live resource information.": "अस्पताल सत्यापित कर्मचारियों की पहुंच का अनुरोध कर सकते हैं और लाइव संसाधन जानकारी प्रकाशित कर सकते हैं।",
    "Protected Operations App": "संरक्षित संचालन ऐप",
    "For authorized response teams": "अधिकृत प्रतिक्रिया टीमों के लिए",
    "Government": "सरकार",
    "Medical": "चिकित्सा",
    "Rescuer": "बचावकर्मी",
    "When you activate SOS, your rescue flow will remain here—even after refresh.": "जब आप SOS सक्रिय करते हैं, तो आपकी बचाव स्थिति यहां रहेगी—रिफ्रेश करने के बाद भी।",
    "Updating rescue flow": "बचाव स्थिति अपडेट की जा रही है",
    "Live rescue flow": "लाइव बचाव स्थिति",
    "Tracking no.": "ट्रैकिंग नंबर",
    "Responder details will appear automatically after Command assigns the mission.": "कमांड द्वारा मिशन सौंपने के बाद रिस्पॉन्डर का विवरण अपने आप दिखाई देगा।",
    "Only your authorized account can add details or message the rescue team.": "केवल आपका अधिकृत खाता विवरण जोड़ सकता है या बचाव दल को संदेश भेज सकता है।",
    "Sign in with the reporting account to add details or message the rescue team.": "विवरण जोड़ने या बचाव दल को संदेश भेजने के लिए रिपोर्टिंग खाते से साइन इन करें।",
    "SOS received": "SOS प्राप्त हुआ",
    "Command is reviewing your location": "कमांड आपके स्थान की समीक्षा कर रहा है",
    "Rescuer assigned": "बचावकर्मी नियुक्त किया गया",
    "Your responder’s profile and live updates appear here": "आपके रिस्पॉन्डर की प्रोफ़ाइल और लाइव अपडेट यहां दिखाई देंगे",
    "Rescue completed": "बचाव कार्य पूरा हुआ",
    "This rescue flow is recorded on this device": "यह बचाव प्रवाह इस उपकरण पर दर्ज किया गया है",
    "Add more details": "अधिक विवरण जोड़ें",
    "People with you, help needed, and useful updates for responders.": "आपके साथ मौजूद लोग, आवश्यक सहायता, और बचाव दल के लिए उपयोगी अपडेट।",
    "Sahayak AI": "सहायक AI",
    "Ask Sahayak AI": "सहायक AI से पूछें",
    "Type your question...": "अपना प्रश्न लिखें...",
    "Send": "भेजें",
    "Close": "बंद करें",
    "Emergency Contacts": "आपातकालीन संपर्क",
    "Edit Profile": "प्रोफ़ाइल संपादित करें",
    "Save Changes": "परिवर्तन सहेजें",
    "Donations": "दान",
    "Donate Now": "अभी दान करें",
  },
  bn: {
    "Sign in to activate": "সক্রিয় করতে সাইন ইন করুন",
    "Record voice note": "ভয়েস নোট রেকর্ড করুন",
    "Speak briefly if typing is difficult": "টাইপ করা কঠিন হলে সংক্ষেপে বলুন",
    "Map preview": "মানচিত্র প্রিভিউ",
    "Map centered on Assam": "মানচিত্র অসমে কেন্দ্রীভূত",
    "Local flood conditions": "স্থানীয় বন্যা পরিস্থিতি",
    "Rainfall now": "এখন বৃষ্টিপাত",
    "Wind speed": "বাতাসের গতি",
    "River level": "নদীর জলস্তর",
    "Unavailable": "অনুপলব্ধ",
    "No reading": "কোনও তথ্য নেই",
    "7-day trend": "৭ দিনের প্রবণতা",
    "View graph": "গ্রাফ দেখুন",
    "Weather forecast": "আবহাওয়ার পূর্বাভাস",
    "Your rescue flow": "আপনার উদ্ধার অগ্রগতি",
    "Saved on this device": "এই ডিভাইসে সংরক্ষিত",
    "No active SOS yet": "এখনও কোনও সক্রিয় SOS নেই",
    "Go to SOS": "SOS-এ যান",
    "Prepare, find support, act early": "প্রস্তুত থাকুন, সহায়তা নিন, আগে পদক্ষেপ নিন",
    "Profile & support": "প্রোফাইল ও সহায়তা",
    "Your safety profile": "আপনার সুরক্ষা প্রোফাইল",
    "Government Command access": "সরকারি কমান্ড প্রবেশ",
    "Continue to Command sign-in": "কমান্ড সাইন-ইন চালিয়ে যান",
    "Return to Victim App": "ভুক্তভোগী অ্যাপে ফিরুন",
    "Safety": "নিরাপত্তা",
    "Nearby hospital information": "কাছাকাছি হাসপাতালের তথ্য",
    "Stay safe, stay informed": "নিরাপদ থাকুন, সচেতন থাকুন",
    "Find verified nearby medical care. For immediate danger, send an SOS now.": "যাচাইকৃত কাছাকাছি চিকিৎসা সেবা খুঁজুন। তাৎক্ষণিক বিপদের জন্য, এখনই SOS পাঠান।",
    "Call 112": "১১২ এ কল করুন",
    "Rapid SOS": "দ্রুত SOS",
    "Verified medical care": "যাচাইকৃত চিকিৎসা সেবা",
    "Nearby hospitals": "কাছাকাছি হাসপাতালসমূহ",
    "Nearest verified hospital shown first": "নিকটতম যাচাইকৃত হাসপাতাল প্রথমে দেখানো হয়েছে",
    "Finding hospitals near you…": "আপনার কাছাকাছি হাসপাতাল খোঁজা হচ্ছে…",
    "Use location to sort hospitals by distance": "দূরত্ব অনুসারে সাজাতে অবস্থান ব্যবহার করুন",
    "Refresh nearby hospitals": "কাছাকাছি হাসপাতাল রিফ্রেশ করুন",
    "Get directions": "দিকনির্দেশ পান",
    "Open": "খোলা",
    "Beds ready": "বেড প্রস্তুত",
    "ICU ready": "ICU প্রস্তুত",
    "of": "এর মধ্যে",
    "total": "মোট",
    "Food": "খাবার",
    "Medicine": "ওষুধ",
    "Water": "জল",
    "Power": "বিদ্যুৎ",
    "Updated": "আপডেট করা হয়েছে",
    "Call": "কল করুন",
    "No call number": "কোন নম্বর নেই",
    "Loading verified hospitals…": "যাচাইকৃত হাসপাতাল লোড হচ্ছে…",
    "No verified hospital listed nearby": "কাছে কোনও যাচাইকৃত হাসপাতাল তালিকাভুক্ত নেই",
    "Flood safety now": "বন্যা নিরাপত্তা",
    "Move higher": "উঁচু স্থানে যান",
    "Leave low ground before water rises.": "জল বাড়ার আগেই নিচু এলাকা ত্যাগ করুন।",
    "Avoid water": "জল এড়িয়ে চলুন",
    "Never walk or drive through moving water.": "প্রবাহিত জলের মধ্য দিয়ে কখনোই হাঁটবেন না বা গাড়ি চালাবেন না।",
    "Keep contact": "যোগাযোগ বজায় রাখুন",
    "Charge your phone and keep emergency numbers ready.": "ফোন চার্জ করুন এবং জরুরি নম্বর প্রস্তুত রাখুন।",
    "Checking conditions": "পরিস্থিতি পরীক্ষা করা হচ্ছে",
    "High rainfall risk": "ভারী বৃষ্টির ঝুঁকি",
    "Elevated rainfall risk": "অধিক বৃষ্টির ঝুঁকি",
    "Current model conditions": "বর্তমান মডেল অবস্থা",
    "Weather source unavailable": "আবহাওয়া উৎস অনুপলব্ধ",
    "chance of rain today": "আজ বৃষ্টির সম্ভাবনা",
    "forecast": "পূর্বাভাস",
    "Official river gauge": "সরকারি নদী গেজ",
    "rising": "বাড়ছে",
    "falling": "কমছে",
    "steady": "স্থির",
    "Local alert": "স্থানীয় সতর্কতা",
    "loading": "লোড হচ্ছে",
    "Assam Safety Network": "অসম নিরাপত্তা নেটওয়ার্ক",
    "Citizen Account": "নাগরিক অ্যাকাউন্ট",
    "Hospital registration": "হাসপাতাল নিবন্ধন",
    "Protected Operations App": "সুরক্ষিত অপারেশন অ্যাপ",
    "Government": "সরকার",
    "Medical": "চিকিৎসা",
    "Rescuer": "উদ্ধারকারী",
    "Live rescue flow": "লাইভ উদ্ধার অগ্রগতি",
    "Tracking no.": "ট্র্যাকিং নম্বর",
    "SOS received": "SOS গৃহীত হয়েছে",
    "Command is reviewing your location": "কমান্ড আপনার অবস্থান পর্যালোচনা করছে",
    "Rescuer assigned": "উদ্ধারকর্মী নিযুক্ত করা হয়েছে",
    "Rescue completed": "উদ্ধার সম্পন্ন হয়েছে",
    "Add more details": "আরও তথ্য যোগ করুন",
    "Sahayak AI": "সহায়ক AI",
    "Ask Sahayak AI": "সহায়ক AI কে জিজ্ঞাসা করুন",
    "Type your question...": "আপনার প্রশ্ন লিখুন...",
    "Send": "পাঠান",
    "Close": "বন্ধ করুন",
    "Emergency Contacts": "জরুরি যোগাযোগ",
    "Edit Profile": "প্রোফাইল সম্পাদনা করুন",
    "Save Changes": "সংরক্ষণ করুন",
    "Donations": "অনুদান",
    "Donate Now": "এখনই দান করুন",
  },
  or: {
    "Sign in to activate": "ସକ୍ରିୟ କରିବା ପାଇଁ ସାଇନ୍ ଇନ୍ କରନ୍ତୁ",
    "Record voice note": "ଭଏସ୍ ନୋଟ୍ ରେକର୍ଡ କରନ୍ତୁ",
    "Speak briefly if typing is difficult": "ଟାଇପ୍ କରିବା କଷ୍ଟକର ହେଲେ ସଂକ୍ଷେପରେ କୁହନ୍ତୁ",
    "Map preview": "ମାନଚିତ୍ର ପୂର୍ବଦୃଶ୍ୟ",
    "Map centered on Assam": "ମାନଚିତ୍ର ଆସାମ ଉପରେ କେନ୍ଦ୍ରିତ",
    "Local flood conditions": "ସ୍ଥାନୀୟ ବନ୍ୟା ପରିସ୍ଥିତି",
    "Rainfall now": "ବର୍ତ୍ତମାନ ବର୍ଷା",
    "Wind speed": "ପବନ ବେଗ",
    "River level": "ନଦୀ ଜଳସ୍ତର",
    "Unavailable": "ଉପଲବ୍ଧ ନାହିଁ",
    "No reading": "କୌଣସି ତଥ୍ୟ ନାହିଁ",
    "7-day trend": "୭ ଦିନର ପ୍ରବଣତା",
    "View graph": "ଗ୍ରାଫ୍ ଦେଖନ୍ତୁ",
    "Weather forecast": "ପାଣିପାଗ ପୂର୍ବାନୁମାନ",
    "Your rescue flow": "ଆପଣଙ୍କ ଉଦ୍ଧାର ସ୍ଥିତି",
    "Saved on this device": "ଏହି ଡିଭାଇସରେ ସଂରକ୍ଷିତ",
    "No active SOS yet": "ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି ସକ୍ରିୟ SOS ନାହିଁ",
    "Go to SOS": "SOS କୁ ଯାଆନ୍ତୁ",
    "Prepare, find support, act early": "ପ୍ରସ୍ତୁତ ରୁହନ୍ତୁ, ସହାୟତା ପାଆନ୍ତୁ, ଶୀଘ୍ର ପଦକ୍ଷେପ ନିଅନ୍ତୁ",
    "Profile & support": "ପ୍ରୋଫାଇଲ୍ ଓ ସହାୟତା",
    "Your safety profile": "ଆପଣଙ୍କ ସୁରକ୍ଷା ପ୍ରୋଫାଇଲ୍",
    "Government Command access": "ସରକାରୀ କମାଣ୍ଡ ପ୍ରବେଶ",
    "Continue to Command sign-in": "କମାଣ୍ଡ ସାଇନ୍ ଇନ୍ ଜାରି ରଖନ୍ତୁ",
    "Return to Victim App": "ପୀଡ଼ିତ ଆପକୁ ଫେରନ୍ତୁ",
    "Safety": "ସୁରକ୍ଷା",
    "Nearby hospital information": "ନିକଟସ୍ଥ ଡାକ୍ତରଖାନା ସୂଚନା",
    "Stay safe, stay informed": "ସୁରକ୍ଷିତ ରୁହନ୍ତୁ, ସଚେତନ ରୁହନ୍ତୁ",
    "Find verified nearby medical care. For immediate danger, send an SOS now.": "ନିକଟସ୍ଥ ଡାକ୍ତରଖାନା ଖୋଜନ୍ତୁ। ଜରୁରୀ ବିପଦ ପାଇଁ ଏବେ SOS ପଠାନ୍ତୁ।",
    "Call 112": "୧୧୨ କୁ କଲ୍ କରନ୍ତୁ",
    "Rapid SOS": "ତ୍ୱରିତ SOS",
    "Verified medical care": "ଯାଞ୍ଚ ହୋଇଥିବା ଚିକିତ୍ସା ସେବା",
    "Nearby hospitals": "ନିକଟସ୍ଥ ଡାକ୍ତରଖାନା",
    "Nearest verified hospital shown first": "ନିକଟତମ ଡାକ୍ତରଖାନା ପ୍ରଥମେ ଦେଖାଯାଇଛି",
    "Finding hospitals near you…": "ନିକଟସ୍ଥ ଡାକ୍ତରଖାନା ଖୋଜାଯାଉଛି…",
    "Use location to sort hospitals by distance": "ଦୂରତା ଅନୁସାରେ ସଜାଇବା ପାଇଁ ଅବସ୍ଥାନ ବ୍ୟବହାର କରନ୍ତୁ",
    "Refresh nearby hospitals": "ଡାକ୍ତରଖାନା ରିଫ୍ରେଶ୍ କରନ୍ତୁ",
    "Get directions": "ରାସ୍ତା ଦେଖନ୍ତୁ",
    "Open": "ଖୋଲା",
    "Beds ready": "ବେଡ୍ ଉପଲବ୍ଧ",
    "ICU ready": "ICU ଉପଲବ୍ଧ",
    "of": "ମଧ୍ୟରୁ",
    "total": "ମୋଟ",
    "Food": "ଖାଦ୍ୟ",
    "Medicine": "ଔଷଧ",
    "Water": "ପାଣି",
    "Power": "ବିଦ୍ୟୁତ୍",
    "Updated": "ଅପଡେଟ୍ ହେଲା",
    "Call": "କଲ୍ କରନ୍ତୁ",
    "No call number": "କୌଣସି ନମ୍ବର ନାହିଁ",
    "Flood safety now": "ବନ୍ୟା ସୁରକ୍ଷା",
    "Move higher": "ଉଚ୍ଚ ସ୍ଥାନକୁ ଯାଆନ୍ତୁ",
    "Leave low ground before water rises.": "ପାଣି ବଢ଼ିବା ପୂର୍ବରୁ ତଳିଆ ଅଞ୍ଚଳ ଛାଡ଼ନ୍ତୁ।",
    "Avoid water": "ପାଣିଠାରୁ ଦୂରେଇ ରୁହନ୍ତୁ",
    "Keep contact": "ସମ୍ପର୍କରେ ରୁହନ୍ତୁ",
    "High rainfall risk": "ପ୍ରବଳ ବର୍ଷା ଆଶଙ୍କା",
    "chance of rain today": "ଆଜି ବର୍ଷା ସମ୍ଭାବନା",
    "forecast": "ପୂର୍ବାନୁମାନ",
    "Local alert": "ସ୍ଥାନୀୟ ସତର୍କତା",
    "Citizen Account": "ନାଗରିକ ଖାତା",
    "Hospital registration": "ଡାକ୍ତରଖାନା ପଞ୍ଜୀକରଣ",
    "Government": "ସରକାର",
    "Medical": "ଚିକିତ୍ସା",
    "Rescuer": "ଉଦ୍ଧାରକାରୀ",
    "Live rescue flow": "ଲାଇଭ୍ ଉଦ୍ଧାର ସ୍ଥିତି",
    "Tracking no.": "ଟ୍ରାକିଂ ନମ୍ବର",
    "SOS received": "SOS ଗ୍ରହଣ କରାଗଲା",
    "Command is reviewing your location": "କମାଣ୍ଡ ଆପଣଙ୍କ ଅବସ୍ଥାନ ଯାଞ୍ଚ କରୁଛି",
    "Rescuer assigned": "ଉଦ୍ଧାରକାରୀ ନିଯୁକ୍ତ",
    "Rescue completed": "ଉଦ୍ଧାର କାର୍ଯ୍ୟ ସମ୍ପୂର୍ଣ୍ଣ",
    "Sahayak AI": "ସହାୟକ AI",
    "Ask Sahayak AI": "ସହାୟକ AI କୁ ପଚାରନ୍ତୁ",
    "Type your question...": "ଆପଣଙ୍କ ପ୍ରଶ୍ନ ଲେଖନ୍ତୁ...",
    "Send": "ପଠାନ୍ତୁ",
    "Close": "ବନ୍ଦ କରନ୍ତୁ",
    "Emergency Contacts": "ଜରୁରୀ ସମ୍ପର୍କ",
    "Edit Profile": "ପ୍ରୋଫାଇଲ୍ ସମ୍ପାଦନ",
    "Save Changes": "ସଂରକ୍ଷଣ କରନ୍ତୁ",
    "Donations": "ଦାନ",
    "Donate Now": "ଏବେ ଦାନ କରନ୍ତୁ",
  },
  mr: {
    "Sign in to activate": "सक्रिय करण्यासाठी साइन इन करा",
    "Record voice note": "व्हॉइस नोट रेकॉर्ड करा",
    "Speak briefly if typing is difficult": "टाइप करणे कठीण असल्यास थोडक्यात बोला",
    "Map preview": "नकाशा पूर्वदृश्य",
    "Map centered on Assam": "नकाशा आसामवर केंद्रित आहे",
    "Local flood conditions": "स्थानिक पूरस्थिती",
    "Rainfall now": "सध्याचा पाऊस",
    "Wind speed": "वाऱ्याचा वेग",
    "River level": "नदीची पातळी",
    "Unavailable": "उपलब्ध नाही",
    "No reading": "कोणतीही नोंद नाही",
    "7-day trend": "७ दिवसांचा कल",
    "View graph": "आलेख पाहा",
    "Weather forecast": "हवामान अंदाज",
    "Your rescue flow": "तुमची बचाव स्थिती",
    "Saved on this device": "या डिव्हाइसवर जतन केले",
    "No active SOS yet": "अजून सक्रिय SOS नाही",
    "Go to SOS": "SOS कडे जा",
    "Prepare, find support, act early": "तयार रहा, मदत मिळवा, लवकर पाऊल उचला",
    "Profile & support": "प्रोफाइल आणि मदत",
    "Your safety profile": "तुमची सुरक्षा प्रोफाइल",
    "Government Command access": "सरकारी कमांड प्रवेश",
    "Continue to Command sign-in": "कमांड साइन इन सुरू ठेवा",
    "Return to Victim App": "पीडित ॲपवर परत जा",
    "Safety": "सुरक्षा",
    "Nearby hospital information": "जवळपासच्या रुग्णालयांची माहिती",
    "Stay safe, stay informed": "सुरक्षित रहा, माहिती मिळवत रहा",
    "Find verified nearby medical care. For immediate danger, send an SOS now.": "जवळपासची वैद्यकीय मदत शोधा. तातडीच्या मदतीसाठी आताच SOS पाठवा.",
    "Call 112": "112 वर कॉल करा",
    "Rapid SOS": "त्वरित SOS",
    "Verified medical care": "सत्यापित वैद्यकीय सेवा",
    "Nearby hospitals": "जवळपासची रुग्णालये",
    "Nearest verified hospital shown first": "जवळचे रुग्णालय प्रथम दाखवले आहे",
    "Finding hospitals near you…": "जवळपास रुग्णालय शोधत आहे…",
    "Use location to sort hospitals by distance": "अंतरावरून क्रमवारी लावण्यासाठी स्थान वापरा",
    "Refresh nearby hospitals": "रुग्णालये रीफ्रेश करा",
    "Get directions": "दिशा मिळवा",
    "Open": "सुरू आहे",
    "Beds ready": "बेड उपलब्ध",
    "ICU ready": "ICU उपलब्ध",
    "of": "पैकी",
    "total": "एकूण",
    "Food": "अन्न",
    "Medicine": "औषध",
    "Water": "पाणी",
    "Power": "वीज",
    "Updated": "अपडेट केले",
    "Call": "कॉल करा",
    "No call number": "नंबर नाही",
    "Flood safety now": "पूर सुरक्षा",
    "Move higher": "उंचावर जा",
    "Leave low ground before water rises.": "पाणी वाढण्यापूर्वी सखल भाग सोडा.",
    "Avoid water": "पाणी टाळा",
    "Keep contact": "संपर्क ठेवा",
    "High rainfall risk": "मुसळधार पावसाचा धोका",
    "chance of rain today": "आज पावसाची शक्यता",
    "forecast": "अंदाज",
    "Local alert": "स्थानिक अलर्ट",
    "Citizen Account": "नागरिक खाते",
    "Hospital registration": "रुग्णालय नोंदणी",
    "Government": "सरकार",
    "Medical": "वैद्यकीय",
    "Rescuer": "बचावकार्य",
    "Live rescue flow": "थेट बचाव स्थिती",
    "Tracking no.": "ट्रॅकिंग क्रमांक",
    "SOS received": "SOS प्राप्त झाले",
    "Command is reviewing your location": "कमांड स्थानाचा आढावा घेत आहे",
    "Rescuer assigned": "बचाव पथक नियुक्त",
    "Rescue completed": "बचाव कार्य पूर्ण",
    "Sahayak AI": "सहायक AI",
    "Ask Sahayak AI": "सहायक AI ला विचारा",
    "Type your question...": "तुमचा प्रश्न लिहा...",
    "Send": "पाठवा",
    "Close": "बंद करा",
    "Emergency Contacts": "आपत्कालीन संपर्क",
    "Edit Profile": "प्रोफाइल संपादित करा",
    "Save Changes": "बदल जतन करा",
    "Donations": "देणगी",
    "Donate Now": "आताच देणगी द्या",
  },
  gu: {
    "Sign in to activate": "સક્રિય કરવા માટે સાઇન ઇન કરો",
    "Record voice note": "વૉઇસ નોટ રેકોર્ડ કરો",
    "Speak briefly if typing is difficult": "ટાઇપ કરવું મુશ્કેલ હોય તો ટૂંકમાં બોલો",
    "Map preview": "નકશાનું પૂર્વદર્શન",
    "Map centered on Assam": "નકશો આસામ પર કેન્દ્રિત છે",
    "Local flood conditions": "સ્થાનિક પૂર સ્થિતિ",
    "Rainfall now": "હાલનો વરસાદ",
    "Wind speed": "પવનની ગતિ",
    "River level": "નદીનું જળસ્તર",
    "Unavailable": "ઉપલબ્ધ નથી",
    "No reading": "કોઈ માપ નથી",
    "7-day trend": "7 દિવસનો વલણ",
    "View graph": "ગ્રાફ જુઓ",
    "Weather forecast": "હવામાન આગાહી",
    "Your rescue flow": "તમારી બચાવ સ્થિતિ",
    "Saved on this device": "આ ઉપકરણમાં સાચવેલ",
    "No active SOS yet": "હજુ કોઈ સક્રિય SOS નથી",
    "Go to SOS": "SOS પર જાઓ",
    "Prepare, find support, act early": "તૈયાર રહો, મદદ મેળવો, વહેલા પગલા લો",
    "Profile & support": "પ્રોફાઇલ અને સહાય",
    "Your safety profile": "તમારી સુરક્ષા પ્રોફાઇલ",
    "Government Command access": "સરકારી કમાન્ડ પ્રવેશ",
    "Continue to Command sign-in": "કમાન્ડ સાઇન ઇન ચાલુ રાખો",
    "Return to Victim App": "પીડિત એપ પર પાછા જાઓ",
    "Safety": "સુરક્ષા",
    "Nearby hospital information": "નજીકની હોસ્પિટલોની માહિતી",
    "Stay safe, stay informed": "સુરક્ષિત રહો, માહિતગાર રહો",
    "Find verified nearby medical care. For immediate danger, send an SOS now.": "નજીકની તબીબી સંભાળ શોધો. તાત્કાલિક જોખમ માટે, અત્યારે જ SOS મોકલો.",
    "Call 112": "112 પર કૉલ કરો",
    "Rapid SOS": "ઝડપી SOS",
    "Verified medical care": "ચકાસાયેલ તબીબી સંભાળ",
    "Nearby hospitals": "નજીકની હોસ્પિટલો",
    "Nearest verified hospital shown first": "નજીકની હોસ્પિટલ પહેલા બતાવી છે",
    "Finding hospitals near you…": "નજીકની હોસ્પિટલ શોધાઈ રહી છે…",
    "Use location to sort hospitals by distance": "અંતર પ્રમાણે ગોઠવવા સ્થાનનો ઉપયોગ કરો",
    "Refresh nearby hospitals": "હોસ્પિટલો રિફ્રેશ કરો",
    "Get directions": "દિશા મેળવો",
    "Open": "ખુલ્લું છે",
    "Beds ready": "બેડ ઉપલબ્ધ",
    "ICU ready": "ICU ઉપલબ્ધ",
    "of": "માંથી",
    "total": "કુલ",
    "Food": "ખોરાક",
    "Medicine": "દવા",
    "Water": "પાણી",
    "Power": "વીજળી",
    "Updated": "અપડેટ થયું",
    "Call": "કૉલ કરો",
    "No call number": "કોઈ નંબર નથી",
    "Flood safety now": "પૂર સુરક્ષા",
    "Move higher": "ઊંચા સ્થાને જાઓ",
    "Leave low ground before water rises.": "પાણી વધે તે પહેલાં નીચાણવાળા વિસ્તાર છોડો.",
    "Avoid water": "પાણીથી બચો",
    "Keep contact": "સંપર્કમાં રહો",
    "High rainfall risk": "ભારે વરસાદનું જોખમ",
    "chance of rain today": "આજે વરસાદની સંભાવના",
    "forecast": "આગાહી",
    "Local alert": "સ્થાનિક એલર્ટ",
    "Citizen Account": "નાગરિક ખાતું",
    "Hospital registration": "હોસ્પિટલ નોંધણી",
    "Government": "સરકાર",
    "Medical": "તબીબી",
    "Rescuer": "બચાવકર્મી",
    "Live rescue flow": "લાઇવ બચાવ સ્થિતિ",
    "Tracking no.": "ટ્રેકિંગ નંબર",
    "SOS received": "SOS મળ્યો",
    "Command is reviewing your location": "કમાન્ડ તમારા સ્થાનની સમીક્ષા કરી રહ્યું છે",
    "Rescuer assigned": "બચાવકર્મી ફાળવાયા",
    "Rescue completed": "બચાવ કાર્ય પૂર્ણ",
    "Sahayak AI": "સહાયક AI",
    "Ask Sahayak AI": "સહાયક AI ને પૂછો",
    "Type your question...": "તમારો પ્રશ્ન લખો...",
    "Send": "મોકલો",
    "Close": "બંધ કરો",
    "Emergency Contacts": "ઇમરજન્સી સંપર્કો",
    "Edit Profile": "પ્રોફાઇલ સંપાદિત કરો",
    "Save Changes": "ફેરફારો સાચવો",
    "Donations": "દાન",
    "Donate Now": "હમણાં દાન કરો",
  },
  ta: {
    "Sign in to activate": "செயல்படுத்த உள்நுழையவும்",
    "Record voice note": "குரல் குறிப்பைப் பதிவு செய்யவும்",
    "Speak briefly if typing is difficult": "தட்டச்சு கடினமாக இருந்தால் சுருக்கமாகப் பேசவும்",
    "Map preview": "வரைபட முன்னோட்டம்",
    "Map centered on Assam": "வரைபடம் அசாமை மையமாகக் கொண்டுள்ளது",
    "Local flood conditions": "உள்ளூர் வெள்ள நிலவரம்",
    "Rainfall now": "தற்போதைய மழை",
    "Wind speed": "காற்றின் வேகம்",
    "River level": "ஆற்று நீர்மட்டம்",
    "Unavailable": "கிடைக்கவில்லை",
    "No reading": "தரவு இல்லை",
    "7-day trend": "7 நாள் போக்கு",
    "View graph": "வரைபடத்தைப் பார்க்கவும்",
    "Weather forecast": "வானிலை முன்னறிவிப்பு",
    "Your rescue flow": "உங்கள் மீட்பு நிலை",
    "Saved on this device": "இந்தச் சாதனத்தில் சேமிக்கப்பட்டது",
    "No active SOS yet": "இதுவரை செயலில் SOS இல்லை",
    "Go to SOS": "SOS-க்கு செல்லவும்",
    "Prepare, find support, act early": "தயாராக இருங்கள், உதவி பெறுங்கள், முன்கூட்டியே செயல்படுங்கள்",
    "Profile & support": "சுயவிவரம் மற்றும் உதவி",
    "Your safety profile": "உங்கள் பாதுகாப்பு சுயவிவரம்",
    "Government Command access": "அரசு கட்டளை அணுகல்",
    "Continue to Command sign-in": "கட்டளை உள்நுழைவைத் தொடரவும்",
    "Return to Victim App": "பாதிக்கப்பட்டோர் செயலிக்கு திரும்பவும்",
    "Safety": "பாதுகாப்பு",
    "Nearby hospital information": "அருகிலுள்ள மருத்துவமனை தகவல்கள்",
    "Stay safe, stay informed": "பாதுகாப்பாக இருங்கள், தகவலுடன் இருங்கள்",
    "Find verified nearby medical care. For immediate danger, send an SOS now.": "அருகிலுள்ள மருத்துவ உதவியைக் கண்டறியவும். உடனடி ஆபத்திற்கு இப்போது SOS அனுப்பவும்.",
    "Call 112": "112 ஐ அழைக்கவும்",
    "Rapid SOS": "விரைவு SOS",
    "Verified medical care": "சரிபார்க்கப்பட்ட மருத்துவ உதவி",
    "Nearby hospitals": "அருகிலுள்ள மருத்துவமனைகள்",
    "Nearest verified hospital shown first": "அருகிலுள்ள மருத்துவமனை முதலில் காட்டப்படுகிறது",
    "Finding hospitals near you…": "மருத்துவமனைகளைத் தேடுகிறது…",
    "Use location to sort hospitals by distance": "தூரம் அடிப்படையில் வரிசைப்படுத்த இருப்பிடத்தைப் பயன்படுத்தவும்",
    "Refresh nearby hospitals": "மருத்துவமனைகளைப் புதுப்பிக்கவும்",
    "Get directions": "வழி பெறவும்",
    "Open": "திறந்துள்ளது",
    "Beds ready": "படுக்கைகள் தயார்",
    "ICU ready": "ICU தயார்",
    "of": "இல்",
    "total": "மொத்தம்",
    "Food": "உணவு",
    "Medicine": "மருந்து",
    "Water": "தண்ணீர்",
    "Power": "மின்சாரம்",
    "Updated": "புதுப்பிக்கப்பட்டது",
    "Call": "அழைக்கவும்",
    "No call number": "எண் இல்லை",
    "Flood safety now": "வெள்ள பாதுகாப்பு",
    "Move higher": "மேடான இடத்திற்கு செல்லவும்",
    "Leave low ground before water rises.": "தண்ணீர் ஏறும் முன் பள்ளமான பகுதியை விட்டு வெளியேறவும்.",
    "Avoid water": "தண்ணீரைத் தவிர்க்கவும்",
    "Keep contact": "தொடர்பில் இருங்கள்",
    "High rainfall risk": "கனமழை ஆபத்து",
    "chance of rain today": "இன்று மழை வாய்ப்பு",
    "forecast": "முன்னறிவிப்பு",
    "Local alert": "உள்ளூர் எச்சரிக்கை",
    "Citizen Account": "குடிமக்கள் கணக்கு",
    "Hospital registration": "மருத்துவமனை பதிவு",
    "Government": "அரசு",
    "Medical": "மருத்துவம்",
    "Rescuer": "மீட்பாளர்",
    "Live rescue flow": "நேரலை மீட்பு நிலை",
    "Tracking no.": "கண்காணிப்பு எண்",
    "SOS received": "SOS பெறப்பட்டது",
    "Command is reviewing your location": "கட்டளை மையம் உங்கள் இருப்பிடத்தை மதிப்பாய்வு செய்கிறது",
    "Rescuer assigned": "மீட்பாளர் நியமிக்கப்பட்டார்",
    "Rescue completed": "மீட்பு நிறைவடைந்தது",
    "Sahayak AI": "சஹாயக் AI",
    "Ask Sahayak AI": "சஹாயக் AI யிடம் கேளுங்கள்",
    "Type your question...": "உங்கள் கேள்வியை உள்ளிடவும்...",
    "Send": "அனுப்புக",
    "Close": "மூடு",
    "Emergency Contacts": "அவசர தொடர்புகள்",
    "Edit Profile": "சுயவிவரத்தைத் திருத்து",
    "Save Changes": "மாற்றங்களைச் சேமி",
    "Donations": "நன்கொடைகள்",
    "Donate Now": "இப்போது நன்கொடை அளிக்கவும்",
  },
  te: {
    "Sign in to activate": "సక్రియం చేయడానికి సైన్ ఇన్ చేయండి",
    "Record voice note": "వాయిస్ నోట్ రికార్డ్ చేయండి",
    "Speak briefly if typing is difficult": "టైప్ చేయడం కష్టమైతే క్లుప్తంగా మాట్లాడండి",
    "Map preview": "మ్యాప్ ప్రివ్యూ",
    "Map centered on Assam": "మ్యాప్ అస్సాంపై కేంద్రీకృతమై ఉంది",
    "Local flood conditions": "స్థానిక వరద పరిస్థితులు",
    "Rainfall now": "ప్రస్తుత వర్షపాతం",
    "Wind speed": "గాలి వేగం",
    "River level": "నది నీటి మట్టం",
    "Unavailable": "అందుబాటులో లేదు",
    "No reading": "డేటా లేదు",
    "7-day trend": "7 రోజుల ధోరణి",
    "View graph": "గ్రాఫ్ చూడండి",
    "Weather forecast": "వాతావరణ అంచనా",
    "Your rescue flow": "మీ రక్షణ స్థితి",
    "Saved on this device": "ఈ పరికరంలో సేవ్ చేయబడింది",
    "No active SOS yet": "ఇంకా సక్రియ SOS లేదు",
    "Go to SOS": "SOS కు వెళ్లండి",
    "Prepare, find support, act early": "సిద్ధంగా ఉండండి, సహాయం పొందండి, ముందుగానే చర్య తీసుకోండి",
    "Profile & support": "ప్రొఫైల్ మరియు సహాయం",
    "Your safety profile": "మీ భద్రత ప్రొఫైల్",
    "Government Command access": "ప్రభుత్వ కమాండ్ ప్రవేశం",
    "Continue to Command sign-in": "కమాండ్ సైన్ ఇన్ కొనసాగించండి",
    "Return to Victim App": "బాధితుల యాప్‌కు తిరిగి వెళ్ళండి",
    "Safety": "భద్రత",
    "Nearby hospital information": "సమీప ఆసుపత్రుల సమాచారం",
    "Stay safe, stay informed": "సురక్షితంగా ఉండండి, సమాచారం తెలుసుకోండి",
    "Find verified nearby medical care. For immediate danger, send an SOS now.": "సమీప వైద్య సంరక్షణను కనుగొనండి. తక్షణ ప్రమాదం కోసం, ఇప్పుడే SOS పంపండి.",
    "Call 112": "112 కు కాల్ చేయండి",
    "Rapid SOS": "త్వరిత SOS",
    "Verified medical care": "ధృవీకరించబడిన వైద్య సంరక్షణ",
    "Nearby hospitals": "సమీప ఆసుపత్రులు",
    "Nearest verified hospital shown first": "సమీప ఆసుపత్రి మొదట చూపబడింది",
    "Finding hospitals near you…": "సమీప ఆసుపత్రులను శోధిస్తోంది…",
    "Use location to sort hospitals by distance": "దూరం ప్రకారం క్రమబద్ధీకరించడానికి స్థానాన్ని ఉపయోగించండి",
    "Refresh nearby hospitals": "ఆసుపత్రులను రిఫ్రెష్ చేయండి",
    "Get directions": "దారి పొందండి",
    "Open": "తెరిచి ఉంది",
    "Beds ready": "బెడ్స్ సిద్ధంగా ఉన్నాయి",
    "ICU ready": "ICU సిద్ధంగా ఉంది",
    "of": "లో",
    "total": "మొత్తం",
    "Food": "ఆహారం",
    "Medicine": "మందులు",
    "Water": "నీరు",
    "Power": "విద్యుత్",
    "Updated": "నవీకరించబడింది",
    "Call": "కాల్ చేయండి",
    "No call number": "నంబర్ లేదు",
    "Flood safety now": "వరద భద్రత",
    "Move higher": "ఎత్తైన ప్రదేశానికి వెళ్ళండి",
    "Leave low ground before water rises.": "నీటి మట్టం పెరగకముందే లోతట్టు ప్రాంతాలను ఖాళీ చేయండి.",
    "Avoid water": "నీటికి దూరంగా ఉండండి",
    "Keep contact": "సంప్రదింపులో ఉండండి",
    "High rainfall risk": "భారీ వర్షపాతం ప్రమాదం",
    "chance of rain today": "ఈరోజు వర్షం పడే అవకాశం",
    "forecast": "అంచనా",
    "Local alert": "స్థానిక హెచ్చరిక",
    "Citizen Account": "పౌర ఖాతా",
    "Hospital registration": "ఆసుపత్రి నమోదు",
    "Government": "ప్రభుత్వం",
    "Medical": "వైద్య",
    "Rescuer": "రక్షకుడు",
    "Live rescue flow": "ప్రత్యక్ష రక్షణ స్థితి",
    "Tracking no.": "ట్రాకింగ్ సంఖ్య",
    "SOS received": "SOS అందింది",
    "Command is reviewing your location": "కమాండ్ మీ స్థానాన్ని సమీక్షిస్తోంది",
    "Rescuer assigned": "రక్షకుడు నియమించబడ్డారు",
    "Rescue completed": "రక్షణ పూర్తయింది",
    "Sahayak AI": "సహాయక్ AI",
    "Ask Sahayak AI": "సహాయక్ AI ని అడగండి",
    "Type your question...": "మీ ప్రశ్నను నమోదు చేయండి...",
    "Send": "పంపండి",
    "Close": "మూసివేయండి",
    "Emergency Contacts": "అత్యవసర పరిచయాలు",
    "Edit Profile": "ప్రొఫైల్ సవరించండి",
    "Save Changes": "మార్పులను సేవ్ చేయండి",
    "Donations": "విరాళాలు",
    "Donate Now": "ఇప్పుడే విరాళం ఇవ్వండి",
  },
  kn: {
    "Sign in to activate": "ಸಕ್ರಿಯಗೊಳಿಸಲು ಸೈನ್ ಇನ್ ಮಾಡಿ",
    "Record voice note": "ಧ್ವನಿ ಟಿಪ್ಪಣಿ ದಾಖಲಿಸಿ",
    "Speak briefly if typing is difficult": "ಟೈಪ್ ಮಾಡುವುದು ಕಷ್ಟವಾದರೆ ಸಂಕ್ಷಿಪ್ತವಾಗಿ ಮಾತನಾಡಿ",
    "Map preview": "ನಕ್ಷೆ ಪೂರ್ವವೀಕ್ಷಣೆ",
    "Map centered on Assam": "ನಕ್ಷೆ ಅಸ್ಸಾಂನಲ್ಲಿ ಕೇಂದ್ರೀಕೃತವಾಗಿದೆ",
    "Local flood conditions": "ಸ್ಥಳೀಯ ಪ್ರವಾಹ ಪರಿಸ್ಥಿತಿಗಳು",
    "Rainfall now": "ಪ್ರಸ್ತುತ ಮಳೆ",
    "Wind speed": "ಗಾಳಿಯ ವೇಗ",
    "River level": "ನದಿಯ ನೀರಿನ ಮಟ್ಟ",
    "Unavailable": "ಲಭ್ಯವಿಲ್ಲ",
    "No reading": "ಯಾವುದೇ ಮಾಹಿತಿ ಇಲ್ಲ",
    "7-day trend": "7 ದಿನಗಳ ಪ್ರವೃತ್ತಿ",
    "View graph": "ಗ್ರಾಫ್ ನೋಡಿ",
    "Weather forecast": "ಹವಾಮಾನ ಮುನ್ಸೂಚನೆ",
    "Your rescue flow": "ನಿಮ್ಮ ರಕ್ಷಣಾ ಸ್ಥಿತಿ",
    "Saved on this device": "ಈ ಸಾಧನದಲ್ಲಿ ಉಳಿಸಲಾಗಿದೆ",
    "No active SOS yet": "ಇನ್ನೂ ಸಕ್ರಿಯ SOS ಇಲ್ಲ",
    "Go to SOS": "SOS ಗೆ ಹೋಗಿ",
    "Prepare, find support, act early": "ಸಿದ್ಧರಿರಿ, ಸಹಾಯ ಪಡೆಯಿರಿ, ಬೇಗ ಕ್ರಮ ತೆಗೆದುಕೊಳ್ಳಿ",
    "Profile & support": "ಪ್ರೊಫೈಲ್ ಮತ್ತು ಸಹಾಯ",
    "Your safety profile": "ನಿಮ್ಮ ಸುರಕ್ಷತಾ ಪ್ರೊಫೈಲ್",
    "Government Command access": "ಸರ್ಕಾರಿ ಕಮಾಂಡ್ ಪ್ರವೇಶ",
    "Continue to Command sign-in": "ಕಮಾಂಡ್ ಸೈನ್ ಇನ್ ಮುಂದುವರಿಸಿ",
    "Return to Victim App": "ಬಾಧಿತ ಆಪ್‌ಗೆ ಹಿಂತಿರುಗಿ",
    "Safety": "ಸುರಕ್ಷತೆ",
    "Nearby hospital information": "ಹತ್ತಿರದ ಆಸ್ಪತ್ರೆ ಮಾಹಿತಿ",
    "Stay safe, stay informed": "ಸುರಕ್ಷಿತವಾಗಿರಿ, ಮಾಹಿತಿ ಪಡೆಯಿರಿ",
    "Find verified nearby medical care. For immediate danger, send an SOS now.": "ಹತ್ತಿರದ ವೈದ್ಯಕೀಯ ನೆರವು ಪಡೆಯಿರಿ. ತಕ್ಷಣದ ಅಪಾಯಕ್ಕಾಗಿ ಈಗಲೇ SOS ಕಳುಹಿಸಿ.",
    "Call 112": "112 ಗೆ ಕರೆ ಮಾಡಿ",
    "Rapid SOS": "ತ್ವರಿತ SOS",
    "Verified medical care": "ದೃಢೀಕೃತ ವೈದ್ಯಕೀಯ ಆರೈಕೆ",
    "Nearby hospitals": "ಹತ್ತಿರದ ಆಸ್ಪತ್ರೆಗಳು",
    "Nearest verified hospital shown first": "ಹತ್ತಿರದ ಆಸ್ಪತ್ರೆಯನ್ನು ಮೊದಲು ತೋರಿಸಲಾಗಿದೆ",
    "Finding hospitals near you…": "ಹತ್ತಿರದ ಆಸ್ಪತ್ರೆಗಳನ್ನು ಹುಡುಕಲಾಗುತ್ತಿದೆ…",
    "Use location to sort hospitals by distance": "ದೂರದ ಪ್ರಕಾರ ವಿಂಗಡಿಸಲು ಸ್ಥಳವನ್ನು ಬಳಸಿ",
    "Refresh nearby hospitals": "ಆಸ್ಪತ್ರೆಗಳನ್ನು ರಿಫ್ರೆಶ್ ಮಾಡಿ",
    "Get directions": "ದಾರಿ ಪಡೆಯಿರಿ",
    "Open": "ತೆರೆದಿದೆ",
    "Beds ready": "ಹಾಸಿಗೆಗಳು ಸಿದ್ಧ",
    "ICU ready": "ICU ಸಿದ್ಧ",
    "of": "ರಲ್ಲಿ",
    "total": "ಒಟ್ಟು",
    "Food": "ಆಹಾರ",
    "Medicine": "ಔಷಧಿ",
    "Water": "ನೀರು",
    "Power": "ವಿದ್ಯುತ್",
    "Updated": "ನವೀಕರಿಸಲಾಗಿದೆ",
    "Call": "ಕರೆ ಮಾಡಿ",
    "No call number": "ಸಂಖ್ಯೆ ಇಲ್ಲ",
    "Flood safety now": "ಪ್ರವಾಹ ಸುರಕ್ಷತೆ",
    "Move higher": "ಎತ್ತರದ ಸ್ಥಳಕ್ಕೆ ಹೋಗಿ",
    "Leave low ground before water rises.": "ನೀರು ಹೆಚ್ಚಾಗುವ ಮೊದಲು ತಗ್ಗು ಪ್ರದೇಶವನ್ನು ಬಿಡಿ.",
    "Avoid water": "ನೀರನ್ನು ತಪ್ಪಿಸಿ",
    "Keep contact": "ಸಂಪರ್ಕದಲ್ಲಿರಿ",
    "High rainfall risk": "ಭಾರೀ ಮಳೆಯ ಅಪಾಯ",
    "chance of rain today": "ಇಂದು ಮಳೆಯ ಸಾಧ್ಯತೆ",
    "forecast": "ಮುನ್ಸೂಚನೆ",
    "Local alert": "ಸ್ಥಳೀಯ ಎಚ್ಚರಿಕೆ",
    "Citizen Account": "ನಾಗರಿಕ ಖಾತೆ",
    "Hospital registration": "ಆಸ್ಪತ್ರೆ ನೋಂದಣಿ",
    "Government": "ಸರ್ಕಾರ",
    "Medical": "ವೈದ್ಯಕೀಯ",
    "Rescuer": "ರಕ್ಷಕ",
    "Live rescue flow": "ಲೈವ್ ರಕ್ಷಣಾ ಸ್ಥಿತಿ",
    "Tracking no.": "ಟ್ರ್ಯಾಕಿಂಗ್ ಸಂಖ್ಯೆ",
    "SOS received": "SOS ಸ್ವೀಕರಿಸಲಾಗಿದೆ",
    "Command is reviewing your location": "ಕಮಾಂಡ್ ನಿಮ್ಮ ಸ್ಥಳವನ್ನು ಪರಿಶೀಲಿಸುತ್ತಿದೆ",
    "Rescuer assigned": "ರಕ್ಷಕರನ್ನು ನಿಯೋಜಿಸಲಾಗಿದೆ",
    "Rescue completed": "ರಕ್ಷಣೆ ಪೂರ್ಣಗೊಂಡಿದೆ",
    "Sahayak AI": "ಸಹಾಯಕ್ AI",
    "Ask Sahayak AI": "ಸಹಾಯಕ್ AI ಗೆ ಕೇಳಿ",
    "Type your question...": "ನಿಮ್ಮ ಪ್ರಶ್ನೆಯನ್ನು ಟೈಪ್ ಮಾಡಿ...",
    "Send": "ಕಳುಹಿಸಿ",
    "Close": "ಮುಚ್ಚಿ",
    "Emergency Contacts": "ತುರ್ತು ಸಂಪರ್ಕಗಳು",
    "Edit Profile": "ಪ್ರೊಫೈಲ್ ಸಂಪಾದಿಸಿ",
    "Save Changes": "ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ",
    "Donations": "ದೇಣಿಗೆ",
    "Donate Now": "ಈಗಲೇ ದೇಣಿಗೆ ನೀಡಿ",
  },
};

const sharedInterfaceTerms: Record<Locale, Record<string, string>> = {
  en: {},
  as: { "Connected": "সংযুক্ত", "Track": "খবৰ লওক", "Safety": "সুৰক্ষা", "More": "অধিক", "Switch to dark theme": "ডাৰ্ক থীমলৈ সলনি কৰক", "Switch to light theme": "লাইট থীমলৈ সলনি কৰক" },
  hi: { "Connected": "कनेक्टेड", "Track": "स्थिति देखें", "Safety": "सुरक्षा", "More": "और", "Switch to dark theme": "डार्क थीम में बदलें", "Switch to light theme": "लाइट थीम में बदलें" },
  bn: { "Connected": "সংযুক্ত", "Track": "ট্র্যাক", "Safety": "নিরাপত্তা", "More": "আরও", "Switch to dark theme": "ডার্ক থিমে বদলান", "Switch to light theme": "লাইট থিমে বদলান" },
  or: { "Connected": "ସଂଯୁକ୍ତ", "Track": "ଟ୍ରାକ୍", "Safety": "ସୁରକ୍ଷା", "More": "ଅଧିକ", "Switch to dark theme": "ଡାର୍କ ଥିମକୁ ବଦଳାନ୍ତୁ", "Switch to light theme": "ଲାଇଟ ଥିମକୁ ବଦଳାନ୍ତୁ" },
  mr: { "Connected": "कनेक्टेड", "Track": "मागोवा", "Safety": "सुरक्षा", "More": "अधिक", "Switch to dark theme": "डार्क थीमवर बदला", "Switch to light theme": "लाइट थीमवर बदला" },
  gu: { "Connected": "જોડાયેલ", "Track": "ટ્રૅક", "Safety": "સુરક્ષા", "More": "વધુ", "Switch to dark theme": "ડાર્ક થીમ પર બદલો", "Switch to light theme": "લાઇટ થીમ પર બદલો" },
  ta: { "Connected": "இணைக்கப்பட்டுள்ளது", "Track": "கண்காணிப்பு", "Safety": "பாதுகாப்பு", "More": "மேலும்", "Switch to dark theme": "இருண்ட தோற்றத்திற்கு மாறவும்", "Switch to light theme": "ஒளி தோற்றத்திற்கு மாறவும்" },
  te: { "Connected": "కనెక్ట్ అయింది", "Track": "ట్రాక్", "Safety": "భద్రత", "More": "మరిన్ని", "Switch to dark theme": "డార్క్ థీమ్‌కు మార్చండి", "Switch to light theme": "లైట్ థీమ్‌కు మార్చండి" },
  kn: { "Connected": "ಸಂಪರ್ಕಗೊಂಡಿದೆ", "Track": "ಟ್ರ್ಯಾಕ್", "Safety": "ಸುರಕ್ಷತೆ", "More": "ಇನ್ನಷ್ಟು", "Switch to dark theme": "ಡಾರ್ಕ್ ಥೀಮ್‌ಗೆ ಬದಲಿಸಿ", "Switch to light theme": "ಲೈಟ್ ಥೀಮ್‌ಗೆ ಬದಲಿಸಿ" },
};

for (const { code } of [{ code: "en" }, { code: "as" }, { code: "hi" }, { code: "bn" }, { code: "or" }, { code: "mr" }, { code: "gu" }, { code: "ta" }, { code: "te" }, { code: "kn" }] as Array<{ code: Locale }>) {
  Object.assign(currentInterfaceTerms[code], sharedInterfaceTerms[code]);
}
