import { MapView } from "@/components/Map";
import { cn } from "@/lib/utils";
import { AlertTriangle, Hospital, MapPin, Radio, TentTree } from "lucide-react";
import { useEffect, useRef, useState } from "react";

type Point = { lat: number; lng: number };
export type OperationalLayers = {
  incidents: Array<{ id: number; publicCode: string; locationLabel: string; latitude: number; longitude: number; severity: "critical" | "high" | "medium" | "low"; status: string }>;
  shelters: Array<{ id: number; name: string; address: string; latitude: number; longitude: number; status: string; capacity: number; occupancy: number }>;
  hospitals: Array<{ id: number; name: string; address: string; latitude: number; longitude: number; status: string; availableEmergencyBeds: number; totalEmergencyBeds: number; availableIcuBeds: number; totalIcuBeds: number }>;
  floodZones: Array<{ id: number; name: string; severity: "critical" | "high" | "medium" | "low"; polygonJson: string }>;
  rescuers: Array<{ user: { id: number; name: string | null }; profile: { callSign: string; lastLatitude: number | null; lastLongitude: number | null; availability: string } }>;
};

const severityColor = { critical: "#c94b45", high: "#e8792e", medium: "#e7ae35", low: "#258e78" };

export default function OperationsMap({ layers, onPickLocation, className, compact = false }: { layers?: OperationalLayers; onPickLocation?: (point: Point) => void; className?: string; compact?: boolean }) {
  const [map, setMap] = useState<google.maps.Map | null>(null);
  const listener = useRef<google.maps.MapsEventListener | null>(null);
  const selectedMarker = useRef<google.maps.Marker | null>(null);
  const mapLayers = layers ?? { incidents: [], shelters: [], hospitals: [], floodZones: [], rescuers: [] };

  useEffect(() => {
    if (!map || !window.google) return;
    const info = new google.maps.InfoWindow(); const markers: google.maps.Marker[] = []; const zones: google.maps.Polygon[] = [];
    mapLayers.incidents.forEach(incident => { const marker = new google.maps.Marker({ map, position: { lat: incident.latitude, lng: incident.longitude }, title: incident.publicCode, icon: { path: google.maps.SymbolPath.CIRCLE, scale: 9, fillColor: severityColor[incident.severity], fillOpacity: 1, strokeColor: "#ffffff", strokeWeight: 2 } }); marker.addListener("click", () => { info.setContent(`<div style="font-family:Manrope,sans-serif;padding:3px"><strong>${incident.publicCode}</strong><br/><span>${incident.locationLabel}</span><br/><small>${incident.status.toUpperCase()} · ${incident.severity.toUpperCase()}</small></div>`); info.open({ map, anchor: marker }); }); markers.push(marker); });
    mapLayers.shelters.forEach(shelter => { const marker = new google.maps.Marker({ map, position: { lat: shelter.latitude, lng: shelter.longitude }, title: shelter.name, icon: { path: google.maps.SymbolPath.BACKWARD_CLOSED_ARROW, scale: 6, fillColor: shelter.status === "open" ? "#258e78" : "#7d8f88", fillOpacity: 1, strokeColor: "#ffffff", strokeWeight: 1.5 } }); marker.addListener("click", () => { info.setContent(`<div style="font-family:Manrope,sans-serif;padding:3px"><strong>${shelter.name}</strong><br/><span>${shelter.address}</span><br/><small>${shelter.occupancy}/${shelter.capacity || "—"} places · ${shelter.status.toUpperCase()}</small></div>`); info.open({ map, anchor: marker }); }); markers.push(marker); });
    mapLayers.hospitals.forEach(hospital => { const color = hospital.status === "open" ? "#255c7d" : hospital.status === "limited" ? "#e7ae35" : hospital.status === "critical" ? "#c94b45" : "#7d8f88"; const marker = new google.maps.Marker({ map, position: { lat: hospital.latitude, lng: hospital.longitude }, title: hospital.name, icon: { path: google.maps.SymbolPath.FORWARD_CLOSED_ARROW, rotation: 270, scale: 6, fillColor: color, fillOpacity: 1, strokeColor: "#ffffff", strokeWeight: 1.5 } }); marker.addListener("click", () => { info.setContent(`<div style="font-family:Manrope,sans-serif;padding:3px"><strong>${hospital.name}</strong><br/><span>${hospital.address}</span><br/><small>ER ${hospital.availableEmergencyBeds}/${hospital.totalEmergencyBeds} · ICU ${hospital.availableIcuBeds}/${hospital.totalIcuBeds} · ${hospital.status.toUpperCase()}</small></div>`); info.open({ map, anchor: marker }); }); markers.push(marker); });
    mapLayers.rescuers.forEach(({ user, profile }) => { if (profile.lastLatitude === null || profile.lastLongitude === null) return; const marker = new google.maps.Marker({ map, position: { lat: profile.lastLatitude, lng: profile.lastLongitude }, title: profile.callSign, icon: { path: google.maps.SymbolPath.FORWARD_CLOSED_ARROW, scale: 6, fillColor: "#255c7d", fillOpacity: 1, strokeColor: "#ffffff", strokeWeight: 1.5 } }); marker.addListener("click", () => { info.setContent(`<div style="font-family:Manrope,sans-serif;padding:3px"><strong>${profile.callSign}</strong><br/><span>${user.name || "Rescue team"}</span><br/><small>${profile.availability.replace("_", " ").toUpperCase()}</small></div>`); info.open({ map, anchor: marker }); }); markers.push(marker); });
    mapLayers.floodZones.forEach(zone => { try { const paths = JSON.parse(zone.polygonJson) as Point[]; const polygon = new google.maps.Polygon({ paths, strokeColor: severityColor[zone.severity], strokeOpacity: 0.9, strokeWeight: 2, fillColor: severityColor[zone.severity], fillOpacity: 0.16, map }); polygon.addListener("click", () => { info.setPosition(paths[0]); info.setContent(`<div style="font-family:Manrope,sans-serif;padding:3px"><strong>${zone.name}</strong><br/><small>Flood severity: ${zone.severity.toUpperCase()}</small></div>`); info.open({ map }); }); zones.push(polygon); } catch { /* Ignore historic invalid polygons. */ } });
    return () => { markers.forEach(marker => marker.setMap(null)); zones.forEach(zone => zone.setMap(null)); };
  }, [map, mapLayers.incidents, mapLayers.rescuers, mapLayers.shelters, mapLayers.hospitals, mapLayers.floodZones]);

  useEffect(() => { if (!map || !onPickLocation) return; listener.current?.remove(); listener.current = map.addListener("click", (event: google.maps.MapMouseEvent) => { if (!event.latLng) return; const point = { lat: event.latLng.lat(), lng: event.latLng.lng() }; selectedMarker.current?.setMap(null); selectedMarker.current = new google.maps.Marker({ map, position: point, title: "Selected location", animation: google.maps.Animation.DROP }); onPickLocation(point); }); return () => { listener.current?.remove(); listener.current = null; }; }, [map, onPickLocation]);

  return <section className={cn("map-shell relative overflow-hidden rounded-2xl border bg-[#dfeee9]", compact ? "h-[320px]" : "h-[520px]", className)}><MapView className="h-full min-h-0" initialCenter={{ lat: 26.2006, lng: 92.9376 }} initialZoom={7} onMapReady={setMap} />{!compact && <div className="pointer-events-none absolute bottom-4 left-4 grid gap-1.5 rounded-xl border border-white/70 bg-white/90 p-3 text-[11px] shadow-lg backdrop-blur"><span className="flex items-center gap-2"><AlertTriangle className="h-3.5 w-3.5 text-[#c94b45]" /> SOS severity</span><span className="flex items-center gap-2"><TentTree className="h-3.5 w-3.5 text-[#258e78]" /> Relief shelter</span><span className="flex items-center gap-2"><Hospital className="h-3.5 w-3.5 text-[#255c7d]" /> Medical resource</span><span className="flex items-center gap-2"><Radio className="h-3.5 w-3.5 text-[#255c7d]" /> Rescue team</span>{onPickLocation && <span className="mt-1 flex items-center gap-2 border-t pt-2 font-semibold text-primary"><MapPin className="h-3.5 w-3.5" /> Click map to set a location</span>}</div>}</section>;
}
