import type { Locale } from "./LanguageContext";

export const currentInterfaceTerms: Record<Locale, Record<string, string>> = {
  en: {},
  as: {
    "Sign in to activate": "সক্ৰিয় কৰিবলৈ ছাইন ইন কৰক", "Record voice note": "কণ্ঠ বাৰ্তা ৰেকৰ্ড কৰক", "Speak briefly if typing is difficult": "টাইপ কৰাটো কঠিন হ’লে সংক্ষিপ্তকৈ কওক", "Map preview": "মানচিত্ৰ পূৰ্বদৃশ্য", "Map centered on Assam": "অসমক কেন্দ্ৰ কৰি মানচিত্ৰ", "Local flood conditions": "স্থানীয় বান পৰিস্থিতি", "Rainfall now": "বৰ্তমান বৰষুণ", "Wind speed": "বতাহৰ গতি", "River level": "নদীৰ জলস্তৰ", "Unavailable": "উপলব্ধ নহয়", "No reading": "কোনো তথ্য নাই", "7-day trend": "৭ দিনৰ ধাৰা", "View graph": "গ্ৰাফ চাওক", "Weather forecast": "বতৰৰ পূৰ্বাভাস", "Your rescue flow": "আপোনাৰ উদ্ধাৰ প্ৰক্ৰিয়া", "Saved on    "Sign in to activate": "सक्रिय करने के लिए साइन इन करें", "Record voice note": "वॉइस नोट रिकॉर्ड करें", "Speak briefly if typing is difficult": "टाइप करना कठिन हो तो संक्षेप में बोलें", "Map preview": "मानचित्र पूर्वावलोकन", "Map centered on Assam": "मानचित्र असम पर केंद्रित है", "Local flood conditions": "स्थानीय बाढ़ की स्थिति", "Rainfall now": "अभी वर्षा", "Wind speed": "हवा की गति", "River level": "नदी का जलस्तर", "Unavailable": "उपलब्ध नहीं", "No reading": "कोई रीडिंग नहीं", "7-day trend": "7-दिन का रुझान", "View graph": "ग्राफ देखें", "Weather forecast": "मौसम पूर्वानुमान", "Your rescue flow": "आपकी बचाव स्थिति", "Saved on this device": "इस डिवाइस पर सहेजा गया", "No active SOS yet": "अभी कोई सक्रिय SOS नहीं", "Go to SOS": "SOS पर जाएँ", "Prepare, find support, act early": "तैयार रहें, सहायता पाएँ, समय रहते कदम उठाएँ", "Profile & support": "प्रोफ़ाइल और सहायता", "Your safety profile": "आपकी सुरक्षा प्रोफ़ाइल", "Government Command access": "सरकारी कमांड पहुंच", "Continue to Command sign-in": "कमांड साइन-इन जारी रखें", "Return to Victim App": "पीड़ित ऐप पर लौटें", "Safety": "सुरक्षा", "Nearby hospital information": "आसपास के अस्पताल की जानकारी", "Stay safe, stay informed": "सुरक्षित रहें, जागरूक रहें", "Find verified nearby medical care. For immediate danger, send an SOS now.": "सत्यापित नजदीकी चिकित्सा देखभाल खोजें। तत्काल खतरे के लिए, अभी SOS भेजें।", "Call 112": "112 पर कॉल करें", "Rapid SOS": "त्वरित SOS", "Verified medical care": "सत्यापित चिकित्सा देखभाल", "Nearby hospitals": "आसपास के अस्पताल", "Nearest verified hospital shown first": "निकटतम सत्यापित अस्पताल पहले दिखाया गया है", "Finding hospitals near you…": "आपके आस-पास अस्पताल खोजा जा रहा है…", "Use location to sort hospitals by distance": "दूरी के अनुसार अस्पताल छांटने के लिए स्थान का उपयोग करें", "Refresh nearby hospitals": "आसपास के अस्पतालों को रिफ्रेश करें", "Get directions": "रास्ता प्राप्त करें", "Open": "खुला है", "Beds ready": "बेड उपलब्ध", "ICU ready": "ICU उपलब्ध", "of": "में से", "total": "कुल", "Food": "भोजन", "Medicine": "दवा", "Water": "पानी", "Power": "बिजली", "Updated": "अपडेट किया गया", "Call": "कॉल करें", "No call number": "कोई कॉल नंबर नहीं", "Loading verified hospitals…": "सत्यापित अस्पताल लोड हो रहे हैं…", "No verified hospital listed nearby": "आसपास कोई सत्यापित अस्पताल सूचीबद्ध नहीं है", "Hospital information appears here after a hospital is verified and staff publish its current capacity.": "अस्पताल के सत्यापित होने और कर्मचारियों द्वारा इसकी वर्तमान क्षमता प्रकाशित करने के बाद अस्पताल की जानकारी यहाँ दिखाई देती है।", "Flood safety now": "बाढ़ से सुरक्षा", "Move higher": "ऊंचे स्थान पर जाएं", "Leave low ground before water rises.": "पानी का स्तर बढ़ने से पहले निचले इलाके को छोड़ दें।", "Avoid water": "पानी से बचें", "Never walk or drive through moving water.": "बहते पानी में कभी न चलें और न ही गाड़ी चलाएं।", "Keep contact": "संपर्क बनाए रखें", "Charge your phone and keep emergency numbers ready.": "अपना फोन चार्ज करें और आपातकालीन नंबर तैयार रखें।", "Checking conditions": "स्थितियों की जाँच की जा रही है", "High rainfall risk": "भारी वर्षा का जोखिम", "Elevated rainfall risk": "अधिक वर्षा का जोखिम", "Current model conditions": "वर्तमान मॉडल की स्थिति", "Weather source unavailable": "मौसम स्रोत अनुपलब्ध", "chance of rain today": "आज बारिश की संभावना", "forecast": "पूर्वानुमान", "Avoid low-lying routes and move early if local authorities advise.": "निचले मार्गों से बचें और यदि स्थानीय अधिकारी सलाह दें तो जल्दी चले जाएं।", "Keep monitoring local authority alerts before travelling.": "यात्रा करने से पहले स्थानीय अधिकारियों के अलर्ट पर नजर रखें।", "Live weather information is temporarily unavailable. Follow official local authority warnings and do not rely on this screen alone.": "लाइव मौसम की जानकारी अस्थायी रूप से अनुपलब्ध है। आधिकारिक स्थानीय चेतावनियों का पालन करें और केवल इस स्क्रीन पर निर्भर न रहें।", "Official river gauge": "आधिकारिक नदी गेज", "rising": "बढ़ रहा है", "falling": "घट रहा है", "steady": "स्थिर", "observed": "देखा गया", "Official source": "आधिकारिक स्रोत", "Weather model loading": "मौसम मॉडल लोड हो रहा है", "Official river-gauge data is temporarily unavailable.": "आधिकारिक नदी-गेज डेटा अस्थायी रूप से अनुपलब्ध है।", "Local alert": "स्थानीय अलर्ट", "loading": "लोड हो रहा है", "Profile & Operations Gateways": "प्रोफ़ाइल और संचालन गेटवे", "Assam Safety Network": "असम सुरक्षा नेटवर्क", "Citizen Account": "नागरिक खाता", "Tap to customize safety profile & emergency contacts": "सुरक्षा प्रोफ़ाइल और आपातकालीन संपर्कों को अनुकूलित करने के लिए टैप करें", "Hospital registration": "अस्पताल पंजीकरण", "Hospitals can request verified staff access and publish live resource information.": "अस्पताल सत्यापित कर्मचारियों की पहुंच का अनुरोध कर सकते हैं और लाइव संसाधन जानकारी प्रकाशित कर सकते हैं।", "Protected Operations App": "संरक्षित संचालन ऐप", "For authorized response teams": "अधिकृत प्रतिक्रिया टीमों के लिए", "Government": "सरकार", "Medical": "चिकित्सा", "Rescuer": "बचावकर्मी", "Your rescue flow": "आपकी बचाव स्थिति", "Saved on this device": "इस डिवाइस पर सहेजा गया", "No active SOS yet": "अभी कोई सक्रिय SOS नहीं", "When you activate SOS, your rescue flow will remain here—even after refresh.": "जब आप SOS सक्रिय करते हैं, तो आपकी बचाव स्थिति यहां रहेगी—रिफ्रेश करने के बाद भी।", "Go to SOS": "SOS पर जाएँ", "Updating rescue flow": "बचाव स्थिति अपडेट की जा रही है", "Live rescue flow": "लाइव बचाव स्थिति", "Tracking no.": "ट्रैकिंग नंबर", "Responder details will appear automatically after Command assigns the mission.": "कमांड द्वारा मिशन सौंपने के बाद रिस्पॉन्डर का विवरण अपने आप दिखाई देगा।", "Only your authorized account can add details or message the rescue team.": "केवल आपका अधिकृत खाता विवरण जोड़ सकता है या बचाव दल को संदेश भेज सकता है।", "Sign in with the reporting account to add details or message the rescue team.": "विवरण जोड़ने या बचाव दल को संदेश भेजने के लिए रिपोर्टिंग खाते से साइन इन करें।", "SOS received": "SOS प्राप्त हुआ", "Command is reviewing your location": "कमांड आपके स्थान की समीक्षा कर रहा है", "Rescuer assigned": "बचावकर्मी नियुक्त किया गया", "Your responder’s profile and live updates appear here": "आपके रिस्पॉन्डर की प्रोफ़ाइल और लाइव अपडेट यहां दिखाई देंगे", "Rescue completed": "बचाव कार्य पूरा हुआ", "This rescue flow is recorded on this device": "यह बचाव प्रवाह इस उपकरण पर दर्ज किया गया है", "Add more details": "अधिक विवरण जोड़ें", "People with you, help needed, and useful updates for responders.": "आपके साथ मौजूद लोग, आवश्यक सहायता, और बचाव दल के लिए उपयोगी अपडेट."��नुपलब्ध", "chance of rain today": "आज बारिश की संभावना", "forecast": "पूर्वानुमान", "Avoid low-lying routes and move early if local authorities advise.": "निचले मार्गों से बचें और यदि स्थानीय अधिकारी सलाह दें तो जल्दी चले जाएं।", "Keep monitoring local authority alerts before travelling.": "यात्रा करने से पहले स्थानीय अधिकारियों के अलर्ट पर नजर रखें।", "Live weather information is temporarily unavailable. Follow official local authority warnings and do not rely on this screen alone.": "लाइव मौसम की जानकारी अस्थायी रूप से अनुपलब्ध है। आधिकारिक स्थानीय चेतावनियों का पालन करें और केवल इस स्क्रीन पर निर्भर न रहें।", "Official river gauge": "आधिकारिक नदी गेज", "rising": "बढ़ रहा है", "falling": "घट रहा है", "steady": "स्थिर", "observed": "देखा गया", "Official source": "आधिकारिक स्रोत", "Weather model loading": "मौसम मॉडल लोड हो रहा है", "Official river-gauge data is temporarily unavailable.": "आधिकारिक नदी-गेज डेटा अस्थायी रूप से अनुपलब्ध है।", "Local alert": "स्थानीय अलर्ट", "loading": "लोड हो रहा है", "Profile & Operations Gateways": "प्रोफ़ाइल और संचालन गेटवे", "Assam Safety Network": "असम सुरक्षा नेटवर्क", "Citizen Account": "नागरिक खाता", "Tap to customize safety profile & emergency contacts": "सुरक्षा प्रोफ़ाइल और आपातकालीन संपर्कों को अनुकूलित करने के लिए टैप करें", "Hospital registration": "अस्पताल पंजीकरण", "Hospitals can request verified staff access and publish live resource information.": "अस्पताल सत्यापित कर्मचारियों की पहुंच का अनुरोध कर सकते हैं और लाइव संसाधन जानकारी प्रकाशित कर सकते हैं।", "Protected Operations App": "संरक्षित संचालन ऐप", "For authorized response teams": "अधिकृत प्रतिक्रिया टीमों के लिए", "Government": "सरकार", "Medical": "चिकित्सा", "Rescuer": "बचावकर्मी", "Your rescue flow": "आपकी बचाव स्थिति", "Saved on this device": "इस डिवाइस पर सहेजा गया", "No active SOS yet": "अभी कोई सक्रिय SOS नहीं", "When you activate SOS, your rescue flow will remain here—even after refresh.": "जब आप SOS सक्रिय करते हैं, तो आपकी बचाव स्थिति यहां रहेगी—रिफ्रेश करने के बाद भी।", "Go to SOS": "SOS पर जाएँ", "Updating rescue flow": "बचाव स्थिति अपडेट की जा रही है", "Live rescue flow": "लाइव बचाव स्थिति", "Tracking no.": "ट्रैकिंग नंबर", "Responder details will appear automatically after Command assigns the mission.": "कमांड द्वारा मिशन सौंपने के बाद रिस्पॉन्डर का विवरण अपने आप दिखाई देगा।", "Only your authorized account can add details or message the rescue team.": "केवल आपका अधिकृत खाता विवरण जोड़ सकता है या बचाव दल को संदेश भेज सकता है।", "Sign in with the reporting account to add details or message the rescue team.": "विवरण जोड़ने या बचाव दल को संदेश भेजने के लिए रिपोर्टिंग खाते से साइन इन करें।", "SOS received": "SOS प्राप्त हुआ", "Command is reviewing your location": "कमांड आपके स्थान की समीक्षा कर रहा है", "Rescuer assigned": "बचावकर्मी नियुक्त किया गया", "Your responder’s profile and live updates appear here": "आपके रिस्पॉन्डर की प्रोफ़ाइल और लाइव अपडेट यहां दिखाई देंगे", "Rescue completed": "बचाव कार्य पूरा हुआ", "This rescue flow is recorded on this device": "यह बचाव प्रवाह इस उपकरण पर दर्ज किया गया है", "Add more details": "अधिक विवरण जोड़ें", "People with you, help needed, and useful updates for responders.": "आपके साथ मौजूद लोग, आवश्यक सहायता, और बचाव दल के लिए उपयोगी अपडेट।"
  },
  bn: {
    "Sign in to activate": "সক্রিয় করতে সাইন ইন করুন", "Record voice note": "ভয়েস নোট রেকর্ড করুন", "Speak briefly if typing is difficult": "টাইপ করা কঠিন হলে সংক্ষেপে বলুন", "Map preview": "মানচিত্র প্রিভিউ", "Map centered on Assam": "মানচিত্র অসমে কেন্দ্রীভূত", "Local flood conditions": "স্থানীয় বন্যা পরিস্থিতি", "Rainfall now": "এখন বৃষ্টিপাত", "Wind speed": "বাতাসের গতি", "River level": "নদীর জলস্তর", "Unavailable": "অনুপলব্ধ", "No reading": "কোনও তথ্য নেই", "7-day trend": "৭ দিনের প্রবণতা", "View graph": "গ্রাফ দেখুন", "Weather forecast": "আবহাওয়ার পূর্বাভাস", "Your rescue flow": "আপনার উদ্ধার অগ্রগতি", "Saved on this device": "এই ডিভাইসে সংরক্ষিত", "No active SOS yet": "এখনও কোনও সক্রিয় SOS নেই", "Go to SOS": "SOS-এ যান", "Prepare, find support, act early": "প্রস্তুত থাকুন, সহায়তা নিন, আগে পদক্ষেপ নিন", "Profile & support": "প্রোফাইল ও সহায়তা", "Your safety profile": "আপনার সুরক্ষা প্রোফাইল", "Government Command access": "সরকারি কমান্ড প্রবেশ", "Continue to Command sign-in": "কমান্ড সাইন-ইন চালিয়ে যান", "Return to Victim App": "ভুক্তভোগী অ্যাপে ফিরুন",
  },
  or: {
    "Sign in to activate": "ସକ୍ରିୟ କରିବା ପାଇଁ ସାଇନ୍ ଇନ୍ କରନ୍ତୁ", "Record voice note": "ଭଏସ୍ ନୋଟ୍ ରେକର୍ଡ କରନ୍ତୁ", "Speak briefly if typing is difficult": "ଟାଇପ୍ କରିବା କଷ୍ଟକର ହେଲେ ସଂକ୍ଷେପରେ କୁହନ୍ତୁ", "Map preview": "ମାନଚିତ୍ର ପୂର୍ବଦୃଶ୍ୟ", "Map centered on Assam": "ମାନଚିତ୍ର ଆସାମ ଉପରେ କେନ୍ଦ୍ରିତ", "Local flood conditions": "ସ୍ଥାନୀୟ ବନ୍ୟା ପରିସ୍ଥିତି", "Rainfall now": "ବର୍ତ୍ତମାନ ବର୍ଷା", "Wind speed": "ପବନ ବେଗ", "River level": "ନଦୀ ଜଳସ୍ତର", "Unavailable": "ଉପଲବ୍ଧ ନାହିଁ", "No reading": "କୌଣସି ତଥ୍ୟ ନାହିଁ", "7-day trend": "୭ ଦିନର ପ୍ରବଣତା", "View graph": "ଗ୍ରାଫ୍ ଦେଖନ୍ତୁ", "Weather forecast": "ପାଣିପାଗ ପୂର୍ବାନୁମାନ", "Your rescue flow": "ଆପଣଙ୍କ ଉଦ୍ଧାର ସ୍ଥିତି", "Saved on this device": "ଏହି ଡିଭାଇସରେ ସଂରକ୍ଷିତ", "No active SOS yet": "ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି ସକ୍ରିୟ SOS ନାହିଁ", "Go to SOS": "SOS କୁ ଯାଆନ୍ତୁ", "Prepare, find support, act early": "ପ୍ରସ୍ତୁତ ରୁହନ୍ତୁ, ସହାୟତା ପାଆନ୍ତୁ, ଶୀଘ୍ର ପଦକ୍ଷେପ ନିଅନ୍ତୁ", "Profile & support": "ପ୍ରୋଫାଇଲ୍ ଓ ସହାୟତା", "Your safety profile": "ଆପଣଙ୍କ ସୁରକ୍ଷା ପ୍ରୋଫାଇଲ୍", "Government Command access": "ସରକାରୀ କମାଣ୍ଡ ପ୍ରବେଶ", "Continue to Command sign-in": "କମାଣ୍ଡ ସାଇନ୍ ଇନ୍ ଜାରି ରଖନ୍ତୁ", "Return to Victim App": "ପୀଡ଼ିତ ଆପକୁ ଫେରନ୍ତୁ",
  },
  mr: {
    "Sign in to activate": "सक्रिय करण्यासाठी साइन इन करा", "Record voice note": "व्हॉइस नोट रेकॉर्ड करा", "Speak briefly if typing is difficult": "टाइप करणे कठीण असल्यास थोडक्यात बोला", "Map preview": "नकाशा पूर्वदृश्य", "Map centered on Assam": "नकाशा आसामवर केंद्रित आहे", "Local flood conditions": "स्थानिक पूरस्थिती", "Rainfall now": "सध्याचा पाऊस", "Wind speed": "वाऱ्याचा वेग", "River level": "नदीची पातळी", "Unavailable": "उपलब्ध नाही", "No reading": "कोणतीही नोंद नाही", "7-day trend": "७ दिवसांचा कल", "View graph": "आलेख पाहा", "Weather forecast": "हवामान अंदाज", "Your rescue flow": "तुमची बचाव स्थिती", "Saved on this device": "या डिव्हाइसवर जतन केले", "No active SOS yet": "अजून सक्रिय SOS नाही", "Go to SOS": "SOS कडे जा", "Prepare, find support, act early": "तयार रहा, मदत मिळवा, लवकर पाऊल उचला", "Profile & support": "प्रोफाइल आणि मदत", "Your safety profile": "तुमची सुरक्षा प्रोफाइल", "Government Command access": "सरकारी कमांड प्रवेश", "Continue to Command sign-in": "कमांड साइन इन सुरू ठेवा", "Return to Victim App": "पीडित ॲपवर परत जा",
  },
  gu: {
    "Sign in to activate": "સક્રિય કરવા માટે સાઇન ઇન કરો", "Record voice note": "વૉઇસ નોટ રેકોર્ડ કરો", "Speak briefly if typing is difficult": "ટાઇપ કરવું મુશ્કેલ હોય તો ટૂંકમાં બોલો", "Map preview": "નકશાનું પૂર્વદર્શન", "Map centered on Assam": "નકશો આસામ પર કેન્દ્રિત છે", "Local flood conditions": "સ્થાનિક પૂર સ્થિતિ", "Rainfall now": "હાલનો વરસાદ", "Wind speed": "પવનની ગતિ", "River level": "નદીનું જળસ્તર", "Unavailable": "ઉપલબ્ધ નથી", "No reading": "કોઈ માપ નથી", "7-day trend": "7 દિવસનો વલણ", "View graph": "ગ્રાફ જુઓ", "Weather forecast": "હવામાન આગાહી", "Your rescue flow": "તમારી બચાવ સ્થિતિ", "Saved on this device": "આ ઉપકરણમાં સાચવેલ", "No active SOS yet": "હજુ કોઈ સક્રિય SOS નથી", "Go to SOS": "SOS પર જાઓ", "Prepare, find support, act early": "તૈયાર રહો, મદદ મેળવો, વહેલા પગલા લો", "Profile & support": "પ્રોફાઇલ અને સહાય", "Your safety profile": "તમારી સુરક્ષા પ્રોફાઇલ", "Government Command access": "સરકારી કમાન્ડ પ્રવેશ", "Continue to Command sign-in": "કમાન્ડ સાઇન ઇન ચાલુ રાખો", "Return to Victim App": "પીડિત એપ પર પાછા જાઓ",
  },
  ta: {
    "Sign in to activate": "செயல்படுத்த உள்நுழையவும்", "Record voice note": "குரல் குறிப்பைப் பதிவு செய்யவும்", "Speak briefly if typing is difficult": "தட்டச்சு கடினமாக இருந்தால் சுருக்கமாகப் பேசவும்", "Map preview": "வரைபட முன்னோட்டம்", "Map centered on Assam": "வரைபடம் அசாமை மையமாகக் கொண்டுள்ளது", "Local flood conditions": "உள்ளூர் வெள்ள நிலவரம்", "Rainfall now": "தற்போதைய மழை", "Wind speed": "காற்றின் வேகம்", "River level": "ஆற்று நீர்மட்டம்", "Unavailable": "கிடைக்கவில்லை", "No reading": "தரவு இல்லை", "7-day trend": "7 நாள் போக்கு", "View graph": "வரைபடத்தைப் பார்க்கவும்", "Weather forecast": "வானிலை முன்னறிவிப்பு", "Your rescue flow": "உங்கள் மீட்பு நிலை", "Saved on this device": "இந்தச் சாதனத்தில் சேமிக்கப்பட்டது", "No active SOS yet": "இதுவரை செயலில் SOS இல்லை", "Go to SOS": "SOS-க்கு செல்லவும்", "Prepare, find support, act early": "தயாராக இருங்கள், உதவி பெறுங்கள், முன்கூட்டியே செயல்படுங்கள்", "Profile & support": "சுயவிவரம் மற்றும் உதவி", "Your safety profile": "உங்கள் பாதுகாப்பு சுயவிவரம்", "Government Command access": "அரசு கட்டளை அணுகல்", "Continue to Command sign-in": "கட்டளை உள்நுழைவைத் தொடரவும்", "Return to Victim App": "பாதிக்கப்பட்டோர் செயலிக்கு திரும்பவும்",
  },
  te: {
    "Sign in to activate": "సక్రియం చేయడానికి సైన్ ইন చేయండి", "Record voice note": "వాయిస్ నోట్ రికార్డ్ చేయండి", "Speak briefly if typing is difficult": "టైప్ చేయడం కష్టమైతే క్లుప్తంగా మాట్లాడండి", "Map preview": "మ్యాప్ ప్రివ్యూ", "Map centered on Assam": "మ్యాప్ అస్సాంపై కేంద్రీకృతమై ఉంది", "Local flood conditions": "స్థానిక వరద పరిస్థితులు", "Rainfall now": "ప్రస్తుత వర్షపాతం", "Wind speed": "గాలి వేగం", "River level": "నది నీటి మట్టం", "Unavailable": "అందుబాటులో లేదు", "No reading": "డేటా లేదు", "7-day trend": "7 రోజుల ధోరణి", "View graph": "గ్రాఫ్ చూడండి", "Weather forecast": "వాతావరణ అంచనా", "Your rescue flow": "మీ రక్షణ స్థితి", "Saved on this device": "ఈ పరికరంలో సేవ్ చేయబడింది", "No active SOS yet": "ఇంకా సక్రియ SOS లేదు", "Go to SOS": "SOS కు వెళ్లండి", "Prepare, find support, act early": "సిద్ధంగా ఉండండి, సహాయం పొందండి, ముందుగానే చర్య తీసుకోండి", "Profile & support": "ప్రొఫైల్ మరియు సహాయం", "Your safety profile": "మీ భద్రత ప్రొఫైల్", "Government Command access": "ప్రభుత్వ కమాండ్ ప్రవేశం", "Continue to Command sign-in": "కమాండ్ సైన్ ఇన్ కొనసాగించండి", "Return to Victim App": "బాధితుల యాప్‌కు తిరిగి వెళ్ళండి",
  },
  kn: {
    "Sign in to activate": "ಸಕ್ರಿಯಗೊಳಿಸಲು ಸೈನ್ ಇನ್ ಮಾಡಿ", "Record voice note": "ಧ್ವನಿ ಟಿಪ್ಪಣಿ ದಾಖಲಿಸಿ", "Speak briefly if typing is difficult": "ಟೈಪ್ ಮಾಡುವುದು ಕಷ್ಟವಾದರೆ ಸಂಕ್ಷಿಪ್ತವಾಗಿ ಮಾತನಾಡಿ", "Map preview": "ನಕ್ಷೆ ಪೂರ್ವವೀಕ್ಷಣೆ", "Map centered on Assam": "ನಕ್ಷೆ ಅಸ್ಸಾಂನಲ್ಲಿ ಕೇಂದ್ರೀಕೃತವಾಗಿದೆ", "Local flood conditions": "ಸ್ಥಳೀಯ ಪ್ರವಾಹ ಪರಿಸ್ಥಿತಿಗಳು", "Rainfall now": "ಪ್ರಸ್ತುತ ಮಳೆ", "Wind speed": "ಗಾಳಿಯ ವೇಗ", "River level": "ನದಿಯ ನೀರಿನ ಮಟ್ಟ", "Unavailable": "ಲಭ್ಯವಿಲ್ಲ", "No reading": "ಯಾವುದೇ ಮಾಹಿತಿ ಇಲ್ಲ", "7-day trend": "7 ದಿನಗಳ ಪ್ರವೃತ್ತಿ", "View graph": "ಗ್ರಾಫ್ ನೋಡಿ", "Weather forecast": "ಹವಾಮಾನ ಮುನ್ಸೂಚನೆ", "Your rescue flow": "ನಿಮ್ಮ ರಕ್ಷಣಾ ಸ್ಥಿತಿ", "Saved on this device": "ಈ ಸಾಧನದಲ್ಲಿ ಉಳಿಸಲಾಗಿದೆ", "No active SOS yet": "ಇನ್ನೂ ಸಕ್ರಿಯ SOS ಇಲ್ಲ", "Go to SOS": "SOS ಗೆ ಹೋಗಿ", "Prepare, find support, act early": "ಸಿದ್ಧರಿರಿ, ಸಹಾಯ ಪಡೆಯಿರಿ, ಬೇಗ ಕ್ರಮ ತೆಗೆದುಕೊಳ್ಳಿ", "Profile & support": "ಪ್ರೊಫೈಲ್ ಮತ್ತು ಸಹಾಯ", "Your safety profile": "ನಿಮ್ಮ ಸುರಕ್ಷತಾ ಪ್ರೊಫೈಲ್", "Government Command access": "ಸರ್ಕಾರಿ ಕಮಾಂಡ್ ಪ್ರವೇಶ", "Continue to Command sign-in": "ಕಮಾಂಡ್ ಸೈನ್ ಇನ್ ಮುಂದುವರಿಸಿ", "Return to Victim App": "ಬಾಧಿತ ಆಪ್‌ಗೆ ಹಿಂತಿರುಗಿ",
  },
};

const sharedInterfaceTerms: Record<Locale, Record<string, string>> = {
  en: {},
  as: {
    "Connected": "সংযুক্ত", "Track": "খবৰ লওক", "Safety": "সুৰক্ষা", "More": "অধিক",
    "Switch to dark theme": "ডাৰ্ক থীমলৈ সলনি কৰক", "Switch to light theme": "লাইট থীমলৈ সলনি কৰক",
    "Delete": "মচি পেলাওক", "Try again": "পুনৰ চেষ্টা কৰক", "Playing": "বাজি আছে",
    "Stop and save voice note": "ৰেকৰ্ডিং বন্ধ কৰক",
    "AI Bot": "AI বট", "Get Help": "সহায় লওক", "Sahayak AI": "সহায়ক AI",
    "Assam Emergency Assistant": "অসম জৰুৰীকালীন সহায়ক", "Ask": "সোধক",
    "Flood safety": "বান সুৰক্ষা", "Find a hospital": "চিকিৎসালয় বিচাৰক", "Rescue assistance": "উদ্ধাৰ সাহায্য",
    "Weather information": "বতৰৰ তথ্য", "What should I do in an emergency?": "জৰুৰীকালীন অৱস্থাত কি কৰিব লাগে?",
    "Suggested Prompts": "প্ৰস্তাৱিত প্ৰশ্ন", "Clear conversation": "কথোপকথন মচক", "Retry": "পুনৰ চেষ্টা",
    "Sahayak AI is thinking…": "সহায়ক AI য়ে ভাবি আছে…",
    "Ask about flood safety, weather, or hospitals…": "বান সুৰক্ষা, বতৰ বা চিকিৎসালয় সম্পৰ্কে সোধক…",
    "Hi! I'm Sahayak AI. How can I help you?": "নমস্কাৰ! মই সহায়ক AI। মই আপোনাক কেনেকৈ সহায় কৰিব পাৰোঁ?",
  },
  hi: {
    "Connected": "कनेक्टेड", "Track": "स्थिति देखें", "Safety": "सुरक्षा", "More": "और",
    "Switch to dark theme": "डार्क थीम में बदलें", "Switch to light theme": "लाइट थीम में बदलें",
    "Delete": "हटाएं", "Try again": "पुनः प्रयास करें", "Playing": "चल रहा है",
    "Stop and save voice note": "रोकें और सहेजें",
    "AI Bot": "AI बॉट", "Get Help": "सहायता लें", "Sahayak AI": "सहायक AI",
    "Assam Emergency Assistant": "असम आपातकालीन सहायक", "Ask": "पूछें",
    "Flood safety": "बाढ़ सुरक्षा", "Find a hospital": "अस्पताल खोजें", "Rescue assistance": "बचाव सहायता",
    "Weather information": "मौसम की जानकारी", "What should I do in an emergency?": "आपातकाल में मुझे क्या करना चाहिए?",
    "Suggested Prompts": "सुझाए गए प्रश्न", "Clear conversation": "बातचीत साफ़ करें", "Retry": "पुनः प्रयास",
    "Sahayak AI is thinking…": "सहायक AI सोच रहा है…",
    "Ask about flood safety, weather, or hospitals…": "बाढ़ सुरक्षा, मौसम या अस्पताल के बारे में पूछें…",
    "Hi! I'm Sahayak AI. How can I help you?": "नमस्ते! मैं सहायक AI हूँ। मैं आपकी क्या मदद कर सकता हूँ?",
  },
  bn: {
    "Connected": "সংযুক্ত", "Track": "ট্র্যাক", "Safety": "নিরাপত্তা", "More": "আরও",
    "Switch to dark theme": "ডার্ক থিমে বদলান", "Switch to light theme": "লাইট থিমে বদলান",
    "Delete": "মুছুন", "Try again": "আবার চেষ্টা করুন", "Playing": "চলছে",
    "Stop and save voice note": "রেকর্ডিং বন্ধ করুন",
    "AI Bot": "AI বট", "Get Help": "সাহায্য নিন", "Sahayak AI": "সহায়ক AI",
    "Assam Emergency Assistant": "আসাম জরুরি সহকারী", "Ask": "জিজ্ঞাসা",
    "Flood safety": "বন্যা সুরক্ষা", "Find a hospital": "হাসপাতাল খুঁজুন", "Rescue assistance": "উদ্ধার সাহায্য",
    "Weather information": "আবহাওয়া তথ্য", "What should I do in an emergency?": "জরুরি অবস্থায় কী করবেন?",
    "Suggested Prompts": "প্রস্তাবিত প্রশ্ন", "Clear conversation": "কথোপকথন সাফ করুন", "Retry": "পুনরায় চেষ্টা",
    "Sahayak AI is thinking…": "সহায়ক AI চিন্তা করছে…",
    "Ask about flood safety, weather, or hospitals…": "বন্যা নিরাপত্তা, আবহাওয়া বা হাসপাতাল সম্পর্কে জানুন…",
    "Hi! I'm Sahayak AI. How can I help you?": "হ্যালো! আমি সহায়ক AI। আপনাকে কীভাবে সাহায্য করতে পারি?",
  },
  or: {
    "Connected": "ସଂଯୁକ୍ତ", "Track": "ଟ୍ରାକ୍", "Safety": "ସୁରକ୍ଷା", "More": "ଅଧିକ",
    "Switch to dark theme": "ଡାର୍କ ଥିମକୁ ବଦଳାନ୍ତୁ", "Switch to light theme": "ଲାଇଟ ଥିମକୁ ବଦଳାନ୍ତୁ",
    "Delete": "ଡିଲିଟ୍ କରନ୍ତୁ", "Try again": "ପୁନର୍ବାର ଚେଷ୍ଟା କରନ୍ତୁ", "Playing": "ଚାଲୁଛି",
    "Stop and save voice note": "ବନ୍ଦ କରି ସେଭ୍ କରନ୍ତୁ",
    "AI Bot": "AI ବଟ୍", "Get Help": "ସହାୟତା ପାଆନ୍ତୁ", "Sahayak AI": "ସହାୟକ AI",
    "Assam Emergency Assistant": "ଆସାମ ଜରୁରୀକାଳୀନ ସହାୟକ", "Ask": "ପଚାରନ୍ତୁ",
    "Flood safety": "ବନ୍ୟା ସୁରକ୍ଷା", "Find a hospital": "ଡାକ୍ତରଖାନା ଖୋଜନ୍ତୁ", "Rescue assistance": "ଉଦ୍ଧାର ସହାୟତା",
    "Weather information": "ପାଣିପାଗ ସୂଚନା", "What should I do in an emergency?": "ଜରୁରୀକାଳୀନ ସ୍ଥିତିରେ କ’ଣ କରିବେ?",
    "Suggested Prompts": "ପ୍ରସ୍ତାବିତ ପ୍ରଶ୍ନ", "Clear conversation": "କଥାବାର୍ତ୍ତା ସଫା କରନ୍ତୁ", "Retry": "ପୁନଃ ପ୍ରୟାସ",
    "Sahayak AI is thinking…": "ସହାୟକ AI ଭାବୁଛି…",
    "Ask about flood safety, weather, or hospitals…": "ବନ୍ୟା ସୁରକ୍ଷା, ପାଣିପାଗ କିମ୍ବା ଡାକ୍ତରଖାନା ବିଷୟରେ ପଚାରନ୍ତୁ…",
    "Hi! I'm Sahayak AI. How can I help you?": "ନମସ୍କାର! ମୁଁ ସହାୟକ AI। ମୁଁ ଆପଣଙ୍କୁ କିପରି ସାହାଯ୍ୟ କରିପାରିବି?",
  },
  mr: {
    "Connected": "कनेक्टेड", "Track": "मागोवा", "Safety": "सुरक्षा", "More": "अधिक",
    "Switch to dark theme": "डार्क थीमवर बदला", "Switch to light theme": "लाइट थीमवर बदला",
    "Delete": "हटवा", "Try again": "पुन्हा प्रयत्न करा", "Playing": "सुरू आहे",
    "Stop and save voice note": "थांबवा आणि जतन करा",
    "AI Bot": "AI बॉट", "Get Help": "मदत मिळवा", "Sahayak AI": "सहायक AI",
    "Assam Emergency Assistant": "आसाम आपत्कालीन सहाय्यक", "Ask": "विचारा",
    "Flood safety": "पूर सुरक्षा", "Find a hospital": "रुग्णालय शोधा", "Rescue assistance": "बचाव मदत",
    "Weather information": "हवामान माहिती", "What should I do in an emergency?": "आपत्कालीन परिस्थितीत काय करावे?",
    "Suggested Prompts": "सुचवलेले प्रश्न", "Clear conversation": "संभाषण साफ करा", "Retry": "पुन्हा प्रयत्न",
    "Sahayak AI is thinking…": "सहायक AI विचार करत आहे…",
    "Ask about flood safety, weather, or hospitals…": "पूर सुरक्षा, हवामान किंवा रुग्णालयाबद्दल विचारा…",
    "Hi! I'm Sahayak AI. How can I help you?": "नमस्कार! मी सहायक AI आहे. मी तुम्हाला कशी मदत करू शकतो?",
  },
  gu: {
    "Connected": "જોડાયેલ", "Track": "ટ્રૅક", "Safety": "સુરક્ષા", "More": "વધુ",
    "Switch to dark theme": "ડાર્ક થીમ પર બદલો", "Switch to light theme": "લાઇટ થીમ પર બદલો",
    "Delete": "કાઢી નાખો", "Try again": "ફરી પ્રયાસ કરો", "Playing": "વાગી રહ્યું છે",
    "Stop and save voice note": "રોકો અને સાચવો",
    "AI Bot": "AI બોટ", "Get Help": "મદદ મેળવો", "Sahayak AI": "સહાયક AI",
    "Assam Emergency Assistant": "આસામ ઇમરજન્સી સહાયક", "Ask": "પૂછો",
    "Flood safety": "પૂર સુરક્ષા", "Find a hospital": "હોસ્પિટલ શોધો", "Rescue assistance": "બચાવ સહાય",
    "Weather information": "હવામાન માહિતી", "What should I do in an emergency?": "ઇમરજન્સીમાં શું કરવું?",
    "Suggested Prompts": "સૂચવેલા પ્રશ્નો", "Clear conversation": "વાતચીત સાફ કરો", "Retry": "ફરી પ્રયાસ",
    "Sahayak AI is thinking…": "સહાયક AI વિચારી રહ્યું છે…",
    "Ask about flood safety, weather, or hospitals…": "પૂર સુરક્ષા, હવામાન કે હોસ્પિટલ વિશે પૂછો…",
    "Hi! I'm Sahayak AI. How can I help you?": "નમસ્તે! હું સહાયક AI છું. હું તમને કેવી રીતે મદદ કરી શકું?",
  },
  ta: {
    "Connected": "இணைக்கப்பட்டுள்ளது", "Track": "கண்காணிப்பு", "Safety": "பாதுகாப்பு", "More": "மேலும்",
    "Switch to dark theme": "இருண்ட தோற்றத்திற்கு மாறவும்", "Switch to light theme": "ஒளி தோற்றத்திற்கு மாறவும்",
    "Delete": "நீக்கு", "Try again": "மீண்டும் முயற்சிக்கவும்", "Playing": "இயங்குகிறது",
    "Stop and save voice note": "நிறுத்தி சேமிக்கவும்",
    "AI Bot": "AI பாட்", "Get Help": "உதவி பெறுக", "Sahayak AI": "சஹாயக் AI",
    "Assam Emergency Assistant": "அசாம் அவசரக்கால உதவியாளர்", "Ask": "கேட்க",
    "Flood safety": "வெள்ள பாதுகாப்பு", "Find a hospital": "மருத்துவமனை கண்டறி", "Rescue assistance": "மீட்பு உதவி",
    "Weather information": "வானிலை தகவல்", "What should I do in an emergency?": "அவசரகாலத்தில் என்ன செய்ய வேண்டும்?",
    "Suggested Prompts": "பரிந்துரைக்கப்பட்ட கேள்விகள்", "Clear conversation": "உரையாடலை அழிக்க", "Retry": "மீண்டும் முயற்சி",
    "Sahayak AI is thinking…": "சஹாயக் AI சிந்திக்கிறது…",
    "Ask about flood safety, weather, or hospitals…": "வெள்ள பாதுகாப்பு, வானிலை அல்லது மருத்துவமனை பற்றி கேட்க…",
    "Hi! I'm Sahayak AI. How can I help you?": "வணக்கம்! நான் சஹாயக் AI. நான் உங்களுக்கு எவ்வாறு உதவ முடியும்?",
  },
  te: {
    "Connected": "కనెక్ట్ అయింది", "Track": "ట్రాక్", "Safety": "భద్రత", "More": "మరిన్ని",
    "Switch to dark theme": "డార్క్ థీమ్‌కు మార్చండి", "Switch to light theme": "లైట్ థీమ్‌కు మార్చండి",
    "Delete": "తొలగించండి", "Try again": "మళ్లీ ప్రయత్నించండి", "Playing": "ప్లే అవుతోంది",
    "Stop and save voice note": "ఆపి భద్రపరచండి",
    "AI Bot": "AI బాట్", "Get Help": "సహాయం పొందండి", "Sahayak AI": "సహాయక్ AI",
    "Assam Emergency Assistant": "అస్సాం అత్యవసర సహాయకుడు", "Ask": "అడగండి",
    "Flood safety": "వరద భద్రత", "Find a hospital": "ఆసుపత్రిని కనుగొనండి", "Rescue assistance": "రక్షణ సహాయం",
    "Weather information": "వాతావరణ సమాచారం", "What should I do in an emergency?": "అత్యవసర పరిస్థితిలో ఏమి చేయాలి?",
    "Suggested Prompts": "సూచించిన ప్రశ్నలు", "Clear conversation": "సంభాషణను క్లియర్ చేయండి", "Retry": "మళ్లీ ప్రయత్నించండి",
    "Sahayak AI is thinking…": "సహాయక్ AI ఆలోచిస్తోంది…",
    "Ask about flood safety, weather, or hospitals…": "వరద భద్రత, వాతావరణం లేదా ఆసుపత్రుల గురించి అడగండి…",
    "Hi! I'm Sahayak AI. How can I help you?": "నమస్తే! నేను సహాయక్ AIని. నేను మీకు ఎలా సహాయపడగలను?",
  },
  kn: {
    "Connected": "ಸಂಪರ್ಕಗೊಂಡಿದೆ", "Track": "ಟ್ರ್ಯಾಕ್", "Safety": "ಸುರಕ್ಷತೆ", "More": "ಇನ್ನಷ್ಟು",
    "Switch to dark theme": "ಡಾರ್ಕ್ ಥೀಮ್‌ಗೆ ಬದಲಿಸಿ", "Switch to light theme": "ಲೈಟ್ ಥೀಮ್‌ಗೆ ಬದಲಿಸಿ",
    "Delete": "ಅಳಿಸಿ", "Try again": "ಮತ್ತೊಮ್ಮೆ ಪ್ರಯತ್ನಿಸಿ", "Playing": "ಪ್ಲೇ ಆಗುತ್ತಿದೆ",
    "Stop and save voice note": "ನಿಲ್ಲಿಸಿ ಉಳಿಸಿ",
    "AI Bot": "AI ಬಾಟ್", "Get Help": "ಸಹಾಯ ಪಡೆಯಿರಿ", "Sahayak AI": "ಸಹಾಯಕ್ AI",
    "Assam Emergency Assistant": "ಅಸ್ಸಾಂ ತುರ್ತು ಸಹಾಯಕ", "Ask": "ಕೇಳಿ",
    "Flood safety": "ಪ್ರವಾಹ ಸುರಕ್ಷತೆ", "Find a hospital": "ಆಸ್ಪತ್ರೆ ಹುಡುಕಿ", "Rescue assistance": "ರಕ್ಷಣಾ ಸಹಾಯ",
    "Weather information": "ಹವಾಮಾನ ಮಾಹಿತಿ", "What should I do in an emergency?": "ತುರ್ತು ಪರಿಸ್ಥಿತಿಯಲ್ಲಿ ಏನು ಮಾಡಬೇಕು?",
    "Suggested Prompts": "ಸೂಚಿಸಲಾದ ಪ್ರಶ್ನೆಗಳು", "Clear conversation": "ಸಂಭಾಷಣೆಯನ್ನು ತೆರವುಗೊಳಿಸಿ", "Retry": "ಮತ್ತೊಮ್ಮೆ ಪ್ರಯತ್ನಿಸಿ",
    "Sahayak AI is thinking…": "ಸಹಾಯಕ್ AI ಯೋಚಿಸುತ್ತಿದೆ…",
    "Ask about flood safety, weather, or hospitals…": "ಪ್ರವಾಹ ಸುರಕ್ಷತೆ, ಹವಾಮಾನ ಅಥವಾ ಆಸ್ಪತ್ರೆಗಳ ಬಗ್ಗೆ ಕೇಳಿ…",
    "Hi! I'm Sahayak AI. How can I help you?": "ನಮಸ್ಕಾರ! ನಾನು ಸಹಾಯಕ AI. ನಾನು ನಿಮಗೆ ಹೇಗೆ ಸಹಾಯ ಮಾಡಲಿ?",
  },
};

for (const { code } of [{ code: "en" }, { code: "as" }, { code: "hi" }, { code: "bn" }, { code: "or" }, { code: "mr" }, { code: "gu" }, { code: "ta" }, { code: "te" }, { code: "kn" }] as Array<{ code: Locale }>) {
  Object.assign(currentInterfaceTerms[code], sharedInterfaceTerms[code]);
}
